/* Generated by scripts/build-client.mjs; edit client.source.js and config.js. */
window.__ModuleLoader__.load({
  id: "dsh-custom-provider",
  factory: (require) => {
    const React = require("react");
const NAMESPACE = "llm-pi-ai";
const COMMON_MODEL_FIELDS = ["name", "contextWindow", "maxTokens", "input", "reasoningEfforts"];
const COMMON_PROVIDER_FIELDS = ["displayName", "baseURL", "api"];
const PROVIDER_ROUTE_PATTERN = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/;

function getAt(value, path) {
  return path.reduce((current, key) => current == null ? undefined : current[key], value);
}

function hasAt(value, path) {
  if (!path.length) return value !== undefined;
  const parent = getAt(value, path.slice(0, -1));
  return parent != null && Object.hasOwn(parent, path.at(-1));
}

function isRecord(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function derivedKeyRef(route) {
  return `${route.toUpperCase().replace(/[^A-Z0-9]+/g, "_")}_API_KEY`;
}

function providerProfile(view, route) {
  return getAt(view.user, ["providers", route]) ?? {};
}

function providerRemovable(view, route) {
  const path = ["providers", route];
  return hasAt(view.user, path) && !hasAt(view.base, path);
}

function providerKind(view, route, directory) {
  const entry = directory.find((item) => item.provider === route);
  if (entry && entry.declared !== true) return "catalog";
  return providerRemovable(view, route) ? "custom" : "inherited";
}

function availableCatalogProviders(directory, configured) {
  const present = new Set(configured);
  return directory.filter((entry) => entry.declared !== true && !present.has(entry.provider));
}

function validateProviderRoute(route, view, reserved = []) {
  if (!PROVIDER_ROUTE_PATTERN.test(route)) throw new Error("Provider ID must start with a lowercase letter and contain only lowercase letters, digits and hyphens");
  if (reserved.includes(route) || hasAt(view.value, ["providers", route])) throw new Error(`Provider ${route} already exists`);
}

function createProviderOperation(view, route, profile, reserved = []) {
  validateProviderRoute(route, view, reserved);
  if (!isRecord(profile)) throw new Error("Provider JSON must be an object");
  return { op: "set", path: ["providers", route], value: { ...profile } };
}

function replaceProviderOperation(view, route, profile) {
  if (!hasAt(view.value, ["providers", route])) throw new Error(`Provider ${route} does not exist`);
  if (!isRecord(profile)) throw new Error("Provider JSON must be an object");
  const previous = providerProfile(view, route);
  const keys = new Set([...Object.keys(previous), ...Object.keys(profile)]);
  return [...keys].filter((key) => key !== "apiKeyEnv" || profile.apiKeyEnv !== undefined || previous.apiKeyEnv !== undefined)
    .filter((key) => JSON.stringify(previous[key]) !== JSON.stringify(profile[key]))
    .map((key) => profile[key] === undefined
      ? { op: "unset", path: ["providers", route, key] }
      : { op: "set", path: ["providers", route, key], value: profile[key] });
}

function patchProviderOperation(view, route, changes) {
  if (!hasAt(view.value, ["providers", route])) throw new Error(`Provider ${route} does not exist`);
  return Object.entries(changes).map(([key, value]) => {
    if (!COMMON_PROVIDER_FIELDS.includes(key)) throw new Error(`Unsupported common provider field: ${key}`);
    return value === undefined
      ? { op: "unset", path: ["providers", route, key] }
      : { op: "set", path: ["providers", route, key], value };
  }).filter((op) => JSON.stringify(getAt(view.user, op.path)) !== JSON.stringify(op.value));
}

function removeProviderOperation(view, route) {
  if (!providerRemovable(view, route)) throw new Error("Inherited providers cannot be removed");
  return { op: "unset", path: ["providers", route] };
}

function addModelOperation(view, route, model) {
  if (!isRecord(model) || typeof model.id !== "string" || !model.id.trim()) throw new Error("Model ID is required");
  if (modelMode(view, route) !== "listed") throw new Error("Only an explicit user model list can be extended");
  const path = ["providers", route, "models"];
  const models = getAt(view.user, path);
  if (models.some((entry) => entry.id === model.id)) throw new Error(`Model ${model.id} already exists`);
  return { op: "set", path, value: [...models, { ...model }] };
}

function removeModelOperation(view, route, modelId) {
  if (modelMode(view, route) !== "listed") throw new Error("Only an explicit user model list can be edited");
  const path = ["providers", route, "models"];
  const models = getAt(view.user, path);
  if (!models.some((entry) => entry.id === modelId)) throw new Error(`Model ${modelId} does not exist`);
  if (models.length === 1) throw new Error("The last model cannot be removed; edit the provider model list explicitly instead");
  return { op: "set", path, value: models.filter((entry) => entry.id !== modelId) };
}

function editObject(value, path, next, restore) {
  const [head, ...tail] = path;
  const result = { ...(isRecord(value) ? value : {}) };
  if (!tail.length) {
    if (restore) delete result[head];
    else result[head] = next;
  } else {
    result[head] = editObject(result[head], tail, next, restore);
    if (restore && Object.keys(result[head]).length === 0) delete result[head];
  }
  return result;
}

function modelMode(view, route) {
  const path = ["providers", route, "models"];
  const userModels = getAt(view.user, path);
  if (Array.isArray(userModels)) return userModels.length ? "listed" : "catalog";
  if (Array.isArray(getAt(view.base, path)) && getAt(view.base, path).length) return "inherited";
  return "catalog";
}

function findModel(models, modelId) {
  return Array.isArray(models) ? models.find((model) => model?.id === modelId) : undefined;
}

function editableModel(view, route, modelId) {
  const prefix = ["providers", route];
  const mode = modelMode(view, route);
  if (mode === "listed") {
    const model = findModel(getAt(view.user, [...prefix, "models"]), modelId);
    if (!model) throw new Error(`Model ${modelId} is not in the configured list`);
    return { ...model };
  }
  if (mode === "inherited") {
    const model = findModel(getAt(view.value, [...prefix, "models"]), modelId);
    if (!model) throw new Error(`Model ${modelId} is not in the inherited list`);
    return { ...model };
  }
  const override = getAt(view.user, [...prefix, "modelOverrides", modelId]);
  return { id: modelId, ...(isRecord(override) ? override : {}) };
}

function effectiveModel(view, route, modelId, catalogModel) {
  const prefix = ["providers", route];
  const mode = modelMode(view, route);
  if (mode === "listed" || mode === "inherited") {
    return findModel(getAt(view.value, [...prefix, "models"]), modelId);
  }
  const profile = getAt(view.value, prefix);
  const override = getAt(profile, ["modelOverrides", modelId]);
  const catalog = catalogModel ? {
    id: catalogModel.id,
    ...(catalogModel.name === undefined ? {} : { name: catalogModel.name }),
    ...(catalogModel.contextWindow === undefined ? {} : { contextWindow: catalogModel.contextWindow }),
    ...(catalogModel.maxTokens === undefined ? {} : { maxTokens: catalogModel.maxTokens }),
    ...(catalogModel.inputModalities === undefined ? {} : { input: [...catalogModel.inputModalities] })
  } : { id: modelId };
  const input = catalog.input ?? profile?.defaultInput;
  return {
    ...(profile?.defaultContextWindow === undefined ? {} : { contextWindow: profile.defaultContextWindow }),
    ...(profile?.defaultMaxTokens === undefined ? {} : { maxTokens: profile.defaultMaxTokens }),
    ...(input === undefined ? {} : { input }),
    ...catalog,
    ...(isRecord(override) ? override : {}),
    id: modelId
  };
}

function modelEntries(view, route, discovered = []) {
  const prefix = ["providers", route];
  const mode = modelMode(view, route);
  const profile = getAt(view.value, prefix);
  if (mode === "listed" || mode === "inherited") {
    return (Array.isArray(profile?.models) ? profile.models : []).map((model) => ({ ...model }));
  }
  const ids = [];
  for (const model of discovered) if (model?.id && !ids.includes(model.id)) ids.push(model.id);
  for (const id of Object.keys(profile?.modelOverrides ?? {})) if (!ids.includes(id)) ids.push(id);
  return ids.map((id) => effectiveModel(view, route, id, discovered.find((model) => model.id === id)));
}

function replaceModelOperation(view, route, modelId, nextModel) {
  if (!isRecord(nextModel)) throw new Error("Model JSON must be an object");
  if (nextModel.id !== modelId) throw new Error(`Model id must remain ${modelId}`);
  const prefix = ["providers", route];
  const mode = modelMode(view, route);
  if (mode === "inherited") throw new Error("The inherited model list cannot be edited without replacing the whole list");
  if (mode === "listed") {
    const path = [...prefix, "models"];
    const models = getAt(view.user, path);
    const index = models.findIndex((model) => model.id === modelId);
    if (index < 0) throw new Error(`Model ${modelId} is not in the configured list`);
    return { op: "set", path, value: models.map((model, at) => at === index ? { ...nextModel } : model) };
  }
  const path = [...prefix, "modelOverrides", modelId];
  const override = Object.fromEntries(Object.entries(nextModel).filter(([key]) => key !== "id"));
  if (Object.keys(override).length === 0) {
    return hasAt(view.user, path) ? { op: "unset", path } : undefined;
  }
  return { op: "set", path, value: override };
}

function patchModelOperation(view, route, modelId, changes) {
  const next = editableModel(view, route, modelId);
  for (const [key, value] of Object.entries(changes)) {
    if (!COMMON_MODEL_FIELDS.includes(key)) throw new Error(`Unsupported common model field: ${key}`);
    if (value === undefined) delete next[key];
    else next[key] = value;
  }
  return replaceModelOperation(view, route, modelId, next);
}

function parseModelJson(text, modelId) {
  let value;
  try { value = JSON.parse(text); }
  catch (error) { throw new Error(`Invalid JSON: ${error.message}`); }
  if (!isRecord(value)) throw new Error("Model JSON must be an object");
  if (value.id !== modelId) throw new Error(`Model id must remain ${modelId}`);
  return value;
}

function mergeLayers(base, user) {
  if (user === undefined) return base;
  if (!isRecord(base) || !isRecord(user)) return user;
  const merged = { ...base };
  for (const [key, value] of Object.entries(user)) merged[key] = mergeLayers(base[key], value);
  return merged;
}

function candidate(view, operation) {
  const operations = Array.isArray(operation) ? operation : operation ? [operation] : [];
  let user = view.user ?? {};
  for (const op of operations) user = editObject(user, op.path, op.value, op.op === "unset");
  return mergeLayers(view.base ?? {}, user);
}

async function commitOperation(api, schema, view, operation, expectedRevision = view.revision) {
  if (!operation) return { kind: "unchanged", view };
  const operations = Array.isArray(operation) ? operation : [operation];
  if (!operations.length) return { kind: "unchanged", view };
  if (expectedRevision !== view.revision) return { kind: "conflict", message: "Settings changed since editing began" };
  let invalid;
  try {
    const root = schema.rehydrate(view.schema);
    invalid = schema.validate(root, candidate(view, operation));
  } catch (error) {
    return { kind: "invalid", message: error.message };
  }
  if (invalid) return { kind: "invalid", message: typeof invalid === "string" ? invalid : JSON.stringify(invalid) };
  try {
    const response = await api.settings.mutate(NAMESPACE, operations, expectedRevision);
    if (response.ok) return { kind: "written", view: response.value };
    return response.error.code === "settings/conflict"
      ? { kind: "conflict", message: response.error.message }
      : { kind: "rejected", message: response.error.message };
  } catch (error) {
    return { kind: "rejected", message: error.message };
  }
}

const h = React.createElement;
const NS = NAMESPACE;
const inject = ["slots", "remote", "remote.settings", "remote.credentials", "remote.llm", "settingsSchema"];
const zh = typeof navigator !== "undefined" && navigator.language?.startsWith("zh");
const tr = (cn, en) => zh ? cn : en;
const STANDARD_REASONING = {
  off: null,
  minimal: "minimal",
  low: "low",
  medium: "medium",
  high: "high",
  xhigh: "xhigh",
  max: "max"
};

const css = `
.dcp-page { max-width: 760px; color: var(--dsw-alias-label-primary, inherit); display: flex; flex-direction: column; gap: 18px; }
.dcp-page h2 { margin: 0; font-size: 16px; font-weight: 500; line-height: 24px; }
.dcp-section { min-width: 0; }
.dcp-section-head { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-bottom: 8px; }
.dcp-section-head h3 { margin: 0; font-size: 14px; font-weight: 500; }
.dcp-list { list-style: none; padding: 0; margin: 0; border-top: .5px solid var(--dsw-alias-border-l4, #8886); }
.dcp-list li { border-bottom: .5px solid var(--dsw-alias-border-l4, #8886); }
.dcp-row { display: flex; align-items: center; justify-content: space-between; min-width: 0; gap: 10px; padding: 4px 0; }
.dcp-row-main { flex: 1; min-width: 0; }
.dcp-row-meta { color: var(--dsw-alias-label-tertiary, #777); font-size: 12px; overflow-wrap: anywhere; }
.dcp-row-actions { display: flex; align-items: center; gap: 4px; flex: none; }
.dcp-selected { color: var(--dsw-alias-brand-primary, #23745a); font-weight: 600; }
.dcp-panel { background: var(--dsw-alias-bg-module-platform, transparent); padding: 14px 16px; border-radius: 6px; margin-top: 12px; }
.dcp-search, .dcp-input, .dcp-select, .dcp-json { box-sizing: border-box; width: 100%; color: inherit; background: var(--dsw-alias-bg-layer-1, transparent); border: .5px solid var(--dsw-alias-border-l4, #8887); border-radius: 6px; font: inherit; }
.dcp-search, .dcp-input, .dcp-select { height: 34px; padding: 0 10px; font-size: 13px; }
.dcp-search:focus, .dcp-input:focus, .dcp-select:focus, .dcp-json:focus { border-color: var(--dsw-alias-brand-primary, #2b8063); outline: none; }
.dcp-search::placeholder, .dcp-input::placeholder { color: var(--dsw-alias-label-dimmed, #777); }
.dcp-provider-button, .dcp-model-button { min-width: 0; border: 0; color: inherit; background: transparent; text-align: left; cursor: pointer; border-radius: 4px; font: inherit; padding: 7px 6px; overflow-wrap: anywhere; }
.dcp-provider-button:hover, .dcp-model-button:hover { background: var(--dsw-alias-interactive-bg-hover, #8882); }
.dcp-provider-button { width: 100%; font-size: 13px; }
.dcp-model-button { width: 100%; font-size: 12px; }
.dcp-content { min-width: 0; }
.dcp-model-head { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; margin-bottom: 14px; }
.dcp-model-title { min-width: 0; }
.dcp-model-title h3 { margin: 0; font-size: 15px; font-weight: 500; line-height: 22px; overflow-wrap: anywhere; }
.dcp-model-id { margin-top: 2px; color: var(--dsw-alias-label-tertiary, #777); font-family: var(--ds-font-family-code, ui-monospace, monospace); font-size: 12px; overflow-wrap: anywhere; }
.dcp-badge { flex: none; border: .5px solid var(--dsw-alias-border-l3, #8886); border-radius: 4px; padding: 2px 6px; color: var(--dsw-alias-label-secondary, inherit); font-size: 11px; line-height: 16px; }
.dcp-tabs { display: flex; gap: 2px; border-bottom: .5px solid var(--dsw-alias-border-l3, #8885); margin-bottom: 18px; }
.dcp-tab { height: 34px; border: 0; border-bottom: 2px solid transparent; color: var(--dsw-alias-label-secondary, inherit); background: transparent; padding: 0 12px; cursor: pointer; font: inherit; font-size: 13px; }
.dcp-tab[aria-selected=true] { border-bottom-color: var(--dsw-alias-brand-primary, #2b8063); color: var(--dsw-alias-label-primary, inherit); font-weight: 500; }
.dcp-form { display: flex; flex-direction: column; gap: 14px; }
.dcp-field { display: grid; grid-template-columns: minmax(120px, 160px) minmax(0, 1fr); align-items: center; gap: 8px 14px; }
.dcp-field label { color: var(--dsw-alias-label-secondary, inherit); font-size: 12px; font-weight: 500; }
.dcp-help { grid-column: 2; margin: -3px 0 0; color: var(--dsw-alias-label-tertiary, #777); font-size: 11px; line-height: 17px; }
.dcp-actions { display: flex; justify-content: flex-end; gap: 8px; padding-top: 4px; }
.dcp-actions-start { justify-content: flex-start; }
.dcp-button { box-sizing: border-box; height: 34px; border: .5px solid var(--dsw-alias-border-l3, #8887); border-radius: 6px; color: inherit; background: transparent; padding: 0 12px; cursor: pointer; font: inherit; font-size: 13px; }
.dcp-button:hover:not(:disabled) { background: var(--dsw-alias-interactive-bg-hover, #8882); }
.dcp-button-primary { border-color: transparent; background: var(--dsw-alias-button-primary-fill, #2b8063); color: var(--dsw-alias-label-primary-foreground, white); }
.dcp-button-primary:hover:not(:disabled) { background: var(--dsw-alias-button-primary-hover, #236b54); }
.dcp-button-danger { color: var(--dsw-alias-state-error-primary, #b42332); border-color: transparent; }
.dcp-button-danger:hover:not(:disabled) { background: var(--dsw-alias-interactive-bg-hover-danger, #b4233218); }
.dcp-button-small { height: 28px; padding: 0 8px; font-size: 12px; }
.dcp-button:disabled, .dcp-input:disabled, .dcp-select:disabled, .dcp-json:disabled { opacity: .48; cursor: default; }
.dcp-json { min-height: 360px; resize: vertical; padding: 12px; font-family: var(--ds-font-family-code, ui-monospace, monospace); font-size: 12px; line-height: 19px; tab-size: 2; }
.dcp-error, .dcp-status, .dcp-empty { margin: 8px 0; font-size: 12px; line-height: 18px; }
.dcp-error { color: var(--dsw-alias-state-error-primary, #b42332); white-space: pre-wrap; }
.dcp-status { color: var(--dsw-alias-state-success-primary, #21835a); }
.dcp-empty { color: var(--dsw-alias-label-tertiary, #777); }
.dcp-skeleton { height: 28px; margin: 5px 6px; border-radius: 5px; background: var(--dsw-alias-interactive-bg-hover, #8882); animation: dcp-pulse 1.2s ease-in-out infinite alternate; }
@keyframes dcp-pulse { to { opacity: .45; } }
.dcp-button:focus-visible, .dcp-provider-button:focus-visible, .dcp-model-button:focus-visible, .dcp-tab:focus-visible { outline: 2px solid var(--dsw-alias-brand-primary, #2b8063); outline-offset: 1px; }
@media (prefers-reduced-motion: reduce) { .dcp-skeleton { animation: none; } }
@media (max-width: 760px) {
  .dcp-section-head, .dcp-row { flex-wrap: wrap; }
  .dcp-panel { padding: 12px; }
  .dcp-field { grid-template-columns: minmax(0, 1fr); gap: 5px; }
  .dcp-help { grid-column: 1; }
}

/* Keep the extension in the same visual language as the built-in Models page. */
.dcp-page { max-width: 720px; gap: 12px; }
.dcp-intro { color: var(--dsw-alias-label-tertiary, #777); margin: 0; font-size: 14px; line-height: 22px; }
.dcp-notice { color: var(--dsw-alias-state-warn-label, #946200); margin: 0; font-size: 12px; line-height: 18px; }
.dcp-saved { color: var(--dsw-alias-state-success-primary, #21835a); margin: 0; font-size: 12px; line-height: 18px; }
.dcp-provider-list { list-style: none; display: flex; flex-direction: column; gap: 8px; margin: 12px 0 0; padding: 0; }
.dcp-provider-card { border: .5px solid var(--dsw-alias-border-l4, #8886); border-radius: 16px; display: flex; flex-direction: column; gap: 12px; padding: 12px 14px; }
.dcp-provider-head { display: flex; align-items: center; gap: 10px; min-width: 0; }
.dcp-provider-identity { display: inline-flex; align-items: center; gap: 6px; min-width: 0; }
.dcp-provider-name { color: var(--dsw-alias-label-primary, inherit); font-size: 14px; font-weight: 500; line-height: 22px; overflow-wrap: anywhere; }
.dcp-provider-route { color: var(--dsw-alias-label-tertiary, #777); font-size: 12px; line-height: 18px; overflow-wrap: anywhere; }
.dcp-provider-tag { border: .5px solid var(--dsw-alias-border-l3, #8886); color: var(--dsw-alias-label-secondary, inherit); border-radius: 4px; flex: none; padding: 1px 6px; font-size: 11px; line-height: 16px; }
.dcp-credential-dot { box-sizing: border-box; border-radius: 50%; flex: none; width: 8px; height: 8px; display: inline-block; }
.dcp-credential-dot-configured { background: var(--dsw-alias-state-success-primary, #21835a); }
.dcp-credential-dot-missing { background: var(--dsw-alias-state-error-primary, #b42332); }
.dcp-provider-actions { display: inline-flex; align-items: center; gap: 4px; margin-left: auto; }
.dcp-provider-editor { background: var(--dsw-alias-bg-module-platform, transparent); border-radius: 12px; display: flex; flex-direction: column; gap: 14px; padding: 14px 16px; }
.dcp-form { display: flex; flex-direction: column; gap: 14px; }
.dcp-field { display: flex; flex-direction: column; gap: 6px; min-width: 0; }
.dcp-field label, .dcp-field-label { color: var(--dsw-alias-label-secondary, inherit); display: inline-flex; align-items: center; gap: 10px; font-size: 12px; font-weight: 500; line-height: 18px; }
.dcp-help { color: var(--dsw-alias-label-tertiary, #777); margin: 0; font-size: 12px; line-height: 18px; }
.dcp-input, .dcp-select, .dcp-search, .dcp-json { border-radius: 8px; }
.dcp-input, .dcp-select, .dcp-search { height: 32px; font-size: 14px; line-height: 22px; }
.dcp-select { max-width: 280px; }
.dcp-button { min-height: 36px; border: 0; border-radius: 18px; font-size: 14px; line-height: 22px; display: inline-flex; align-items: center; justify-content: center; gap: 4px; }
.dcp-button:hover:not(:disabled) { background: var(--dsw-alias-interactive-bg-hover-solid, #8882); }
.dcp-button-small { min-height: 28px; border-radius: 14px; padding: 0 10px; font-size: 12px; line-height: 18px; }
.dcp-button:disabled { opacity: .4; }
.dcp-actions { display: flex; justify-content: flex-end; flex-wrap: wrap; gap: 8px; }
.dcp-customized { border-top: .5px solid var(--dsw-alias-border-l2, #8885); padding-top: 10px; }
.dcp-customized-summary { cursor: pointer; width: fit-content; color: var(--dsw-alias-label-secondary, inherit); border-radius: 6px; display: flex; align-items: center; gap: 6px; margin-left: -4px; padding: 2px 4px; font-size: 12px; font-weight: 500; line-height: 18px; list-style: none; }
.dcp-customized-summary::-webkit-details-marker { display: none; }
.dcp-customized-summary::before { content: ""; border-bottom: 1.5px solid; border-right: 1.5px solid; width: 5px; height: 5px; transform: rotate(-45deg) translate(-1px, -1px); transition: transform .12s; }
.dcp-customized[open] > .dcp-customized-summary::before { transform: rotate(45deg) translate(-1px, -1px); }
.dcp-customized-summary:hover { color: var(--dsw-alias-label-primary, inherit); }
.dcp-customized-body { display: flex; flex-direction: column; gap: 12px; padding-top: 12px; }
.dcp-model-catalog { border-top: .5px solid var(--dsw-alias-border-l2, #8885); display: flex; flex-direction: column; gap: 10px; padding-top: 12px; }
.dcp-model-catalog-head { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; }
.dcp-model-catalog-heading { display: flex; flex-direction: column; gap: 2px; }
.dcp-model-catalog-title { color: var(--dsw-alias-label-secondary, inherit); font-size: 12px; font-weight: 500; line-height: 18px; }
.dcp-model-catalog-meta, .dcp-model-empty { color: var(--dsw-alias-label-tertiary, #777); margin: 0; font-size: 12px; line-height: 18px; }
.dcp-model-list { display: flex; flex-direction: column; gap: 8px; }
.dcp-model-entry { border: .5px solid var(--dsw-alias-border-l4, #8886); border-radius: 10px; padding: 6px; }
.dcp-model-row { display: grid; grid-template-columns: minmax(0, 1.4fr) minmax(0, 1fr) auto auto; align-items: center; gap: 6px; }
.dcp-model-row .dcp-input { min-width: 0; }
.dcp-model-advanced { display: flex; flex-direction: column; gap: 12px; padding: 10px 4px 2px; }
.dcp-model-advanced .dcp-form { gap: 12px; }
.dcp-icon-button { box-sizing: border-box; width: 28px; height: 28px; min-height: 28px; color: var(--dsw-alias-label-tertiary, #777); padding: 0; border-radius: 6px; }
.dcp-icon-button:hover:not(:disabled) { color: var(--dsw-alias-label-primary, inherit); }
.dcp-icon-button-danger:hover:not(:disabled) { color: var(--dsw-alias-state-error-primary, #b42332); background: var(--dsw-alias-interactive-bg-hover-danger, #b4233218); }
.dcp-model-empty { border: 1px dashed var(--dsw-alias-border-l3, #8886); border-radius: 8px; text-align: center; padding: 12px; }
.dcp-add-block { display: flex; flex-direction: column; gap: 12px; }
.dcp-add-actions { display: flex; flex-wrap: wrap; gap: 10px; }
.dcp-add-option { border: 1px dashed var(--dsw-alias-border-l3, #8886); border-radius: 16px; flex: 1 1 0; min-width: 180px; min-height: 44px; }
.dcp-add-card { background: var(--dsw-alias-bg-module-platform, transparent); border-radius: 12px; display: flex; flex-direction: column; gap: 14px; padding: 14px 16px; }
.dcp-json { min-height: 260px; }
.dcp-error, .dcp-status, .dcp-empty { margin: 0; }
.dcp-button:focus-visible, .dcp-input:focus-visible, .dcp-select:focus-visible, .dcp-search:focus-visible, .dcp-customized-summary:focus-visible { box-shadow: 0 0 0 2px var(--dsw-alias-border-l3, #8886); outline: none; }
@media (max-width: 560px) {
  .dcp-provider-card, .dcp-provider-editor, .dcp-add-card { padding: 12px; }
  .dcp-provider-head { align-items: flex-start; flex-wrap: wrap; }
  .dcp-provider-actions { width: 100%; margin-left: 0; justify-content: flex-end; }
  .dcp-model-row { grid-template-columns: minmax(0, 1fr) auto auto; }
  .dcp-model-row .dcp-model-name { grid-column: 1 / -1; }
  .dcp-add-option { min-width: 0; }
}
`;

function sameJson(left, right) {
  return JSON.stringify(left) === JSON.stringify(right);
}

function inputMode(value) {
  if (!Array.isArray(value) || value.length === 0) return "inherit";
  if (value.length === 1 && value[0] === "text") return "text";
  if (value.includes("text") && value.includes("image")) return "image";
  return "custom";
}

function reasoningMode(value) {
  if (value === undefined) return "inherit";
  if (value === false) return "disabled";
  if (sameJson(value, STANDARD_REASONING)) return "standard";
  return "custom";
}

function commonDraft(source) {
  return {
    name: typeof source.name === "string" ? source.name : "",
    contextWindow: source.contextWindow === undefined ? "" : String(source.contextWindow),
    maxTokens: source.maxTokens === undefined ? "" : String(source.maxTokens),
    input: inputMode(source.input),
    reasoning: reasoningMode(source.reasoningEfforts)
  };
}

function positiveInteger(text, label) {
  if (text.trim() === "") return undefined;
  const value = Number(text);
  if (!Number.isSafeInteger(value) || value <= 0) throw new Error(tr(`${label}必须是正整数`, `${label} must be a positive integer`));
  return value;
}

function CommonEditor({ source, effective, readOnly, busy, save }) {
  const sourceKey = JSON.stringify(source);
  const initial = () => commonDraft(source);
  const [draft, setDraft] = React.useState(initial);
  const [dirty, setDirty] = React.useState(false);
  const [failure, setFailure] = React.useState("");
  const [saved, setSaved] = React.useState(false);
  React.useEffect(() => {
    if (!dirty) setDraft(initial());
  }, [sourceKey]);
  const change = (key, value) => {
    setDraft((current) => ({ ...current, [key]: value }));
    setDirty(true);
    setFailure("");
    setSaved(false);
  };
  const submit = async (restore = false) => {
    try {
      const changes = restore ? Object.fromEntries(COMMON_MODEL_FIELDS.map((key) => [key, undefined])) : {
        name: draft.name.trim() || undefined,
        contextWindow: positiveInteger(draft.contextWindow, tr("上下文窗口", "Context window")),
        maxTokens: positiveInteger(draft.maxTokens, tr("输出上限", "Output limit")),
        input: draft.input === "inherit" ? undefined : draft.input === "text" ? ["text"] :
          draft.input === "image" ? ["text", "image"] : source.input,
        reasoningEfforts: draft.reasoning === "inherit" ? undefined : draft.reasoning === "disabled" ? false :
          draft.reasoning === "standard" ? STANDARD_REASONING : source.reasoningEfforts
      };
      const error = await save(changes);
      setFailure(error ?? "");
      setSaved(!error);
      if (!error) setDirty(false);
    } catch (error) {
      setFailure(error.message);
      setSaved(false);
    }
  };
  const disabled = readOnly || busy;
  return h("div", { className: "dcp-form" },
    h("div", { className: "dcp-field" },
      h("label", { htmlFor: "dcp-name" }, tr("模型名称", "Model name")),
      h("input", { id: "dcp-name", className: "dcp-input", value: draft.name, disabled,
        placeholder: effective?.name ?? source.id, onChange: (event) => change("name", event.target.value) })),
    h("div", { className: "dcp-field" },
      h("label", { htmlFor: "dcp-reasoning" }, tr("推理能力", "Reasoning")),
      h("select", { id: "dcp-reasoning", className: "dcp-select", value: draft.reasoning, disabled,
        onChange: (event) => change("reasoning", event.target.value) },
        h("option", { value: "inherit" }, tr("继承提供方或目录", "Inherit provider or catalog")),
        h("option", { value: "disabled" }, tr("不支持推理", "Reasoning disabled")),
        h("option", { value: "standard" }, tr("标准推理档位", "Standard reasoning levels")),
        draft.reasoning === "custom" ? h("option", { value: "custom" }, tr("自定义档位（高级 JSON）", "Custom levels (Advanced JSON)")) : null)),
    h("div", { className: "dcp-field" },
      h("label", { htmlFor: "dcp-input" }, tr("输入类型", "Input types")),
      h("select", { id: "dcp-input", className: "dcp-select", value: draft.input, disabled,
        onChange: (event) => change("input", event.target.value) },
        h("option", { value: "inherit" }, tr("继承提供方或目录", "Inherit provider or catalog")),
        h("option", { value: "text" }, tr("文本", "Text")),
        h("option", { value: "image" }, tr("文本和图片", "Text and image")),
        draft.input === "custom" ? h("option", { value: "custom" }, tr("自定义（高级 JSON）", "Custom (Advanced JSON)")) : null)),
    h("div", { className: "dcp-field" },
      h("label", { htmlFor: "dcp-context" }, tr("上下文窗口", "Context window")),
      h("input", { id: "dcp-context", className: "dcp-input", type: "number", min: "1", step: "1",
        value: draft.contextWindow, disabled, placeholder: effective?.contextWindow === undefined ? "" : String(effective.contextWindow),
        onChange: (event) => change("contextWindow", event.target.value) })),
    h("div", { className: "dcp-field" },
      h("label", { htmlFor: "dcp-output" }, tr("输出上限", "Output limit")),
      h("input", { id: "dcp-output", className: "dcp-input", type: "number", min: "1", step: "1",
        value: draft.maxTokens, disabled, placeholder: effective?.maxTokens === undefined ? "" : String(effective.maxTokens),
        onChange: (event) => change("maxTokens", event.target.value) })),
    failure ? h("p", { className: "dcp-error", role: "alert" }, failure) : null,
    saved ? h("p", { className: "dcp-status", role: "status" }, tr("已保存", "Saved")) : null,
    readOnly ? h("p", { className: "dcp-empty" }, tr("此模型来自组合配置，当前只读", "This model is inherited from the composition and is read-only")) :
      h("div", { className: "dcp-actions" },
        h("button", { type: "button", className: "dcp-button", disabled: busy,
          onClick: () => submit(true) }, tr("恢复继承", "Restore inherited")),
        h("button", { type: "button", className: "dcp-button dcp-button-primary", disabled: busy || !dirty,
          onClick: () => submit(false) }, busy ? tr("保存中", "Saving") : tr("保存", "Save"))));
}

function AdvancedEditor({ source, readOnly, busy, save }) {
  const sourceKey = JSON.stringify(source);
  const formatted = () => JSON.stringify(source, null, 2);
  const [draft, setDraft] = React.useState(formatted);
  const [dirty, setDirty] = React.useState(false);
  const [failure, setFailure] = React.useState("");
  const [saved, setSaved] = React.useState(false);
  React.useEffect(() => {
    if (!dirty) setDraft(formatted());
  }, [sourceKey]);
  const format = () => {
    try {
      const value = parseModelJson(draft, source.id);
      setDraft(JSON.stringify(value, null, 2));
      setFailure("");
    } catch (error) { setFailure(error.message); }
  };
  const submit = async () => {
    try {
      const value = parseModelJson(draft, source.id);
      const error = await save(value);
      setFailure(error ?? "");
      setSaved(!error);
      if (!error) setDirty(false);
    } catch (error) {
      setFailure(error.message);
      setSaved(false);
    }
  };
  return h("div", null,
    h("textarea", { className: "dcp-json", value: draft, disabled: readOnly || busy, spellCheck: false,
      "aria-label": tr("当前模型 JSON", "Current model JSON"), onChange: (event) => {
        setDraft(event.target.value); setDirty(true); setFailure(""); setSaved(false);
      } }),
    failure ? h("p", { className: "dcp-error", role: "alert" }, failure) : null,
    saved ? h("p", { className: "dcp-status", role: "status" }, tr("已保存", "Saved")) : null,
    readOnly ? h("p", { className: "dcp-empty" }, tr("此模型来自组合配置，当前只读", "This model is inherited from the composition and is read-only")) :
      h("div", { className: "dcp-actions" },
        h("button", { type: "button", className: "dcp-button", disabled: busy, onClick: format }, tr("格式化", "Format")),
        h("button", { type: "button", className: "dcp-button dcp-button-primary", disabled: busy || !dirty,
          onClick: submit }, busy ? tr("保存中", "Saving") : tr("保存 JSON", "Save JSON"))));
}

function protocolChoices(view, schema) {
  if (!view) return [];
  const node = schema.nodeAtPath(schema.rehydrate(view.schema), ["providers", "\0probe", "api"]);
  return node?.type === "union" ? node.list.map((entry) => entry.value).filter((value) => typeof value === "string") : [];
}

function validUrl(value) {
  try { return ["http:", "https:"].includes(new URL(value).protocol); }
  catch { return false; }
}

function keyFailure(value) {
  if (!value.length) return "";
  if (value !== value.trim() || !/^[\x21-\x7e]+$/.test(value) || /^[A-Z][A-Z0-9_]*=[^=]/.test(value) ||
    (["'", '"', "`"].includes(value[0]) && value.endsWith(value[0]) && value.length > 1)) {
    return tr("API Key 格式无效，请仅输入密钥本身", "Invalid API key; enter the key value only");
  }
  return "";
}

function CreateProvider({ view, schema, available, busy, api, onWrite, onClose, initialKind }) {
  const [kind, setKind] = React.useState(initialKind ?? (available.length ? "catalog" : "custom"));
  const [chosen, setChosen] = React.useState(available[0]?.provider ?? "");
  const [route, setRoute] = React.useState("");
  const [name, setName] = React.useState("");
  const [baseURL, setBaseURL] = React.useState("");
  const protocols = React.useMemo(() => protocolChoices(view, schema), [view?.schema, schema]);
  const [protocol, setProtocol] = React.useState("");
  const [modelId, setModelId] = React.useState("");
  const [key, setKey] = React.useState("");
  const [committed, setCommitted] = React.useState("");
  const [failure, setFailure] = React.useState("");
  const [submitting, setSubmitting] = React.useState(false);
  const submit = async () => {
    setFailure(""); setSubmitting(true);
    try {
      const id = committed || (kind === "catalog" ? chosen : route.trim());
      const ref = derivedKeyRef(id);
      const invalidKey = keyFailure(key);
      if (invalidKey) throw new Error(invalidKey);
      if (!committed) {
        const profile = kind === "catalog" ? {} : {
          ...(name.trim() ? { displayName: name.trim() } : {}),
          api: protocol || protocols[0], baseURL: baseURL.trim(), models: [{ id: modelId.trim() }]
        };
        if (kind === "custom" && (!validUrl(baseURL.trim()) || !protocols.includes(profile.api) || !modelId.trim())) {
          throw new Error(tr("请填写有效的地址、协议和首个模型 ID", "Enter a valid endpoint, protocol, and first model ID"));
        }
        if (key) profile.apiKeyEnv = ref;
        const operation = createProviderOperation(view, id, profile,
          kind === "custom" ? available.map((entry) => entry.provider) : []);
        const error = await onWrite(operation);
        if (error) throw new Error(error);
        setCommitted(id);
      }
      if (key) {
        const result = await api.credentials.set(ref, key);
        if (!result.ok) throw new Error(result.error.message);
        setKey("");
      }
      onClose(id);
    } catch (error) { setFailure(error.message); }
    finally { setSubmitting(false); }
  };
  const disabled = busy || submitting || !!committed;
  return h("div", { className: "dcp-form" },
    h("div", { className: "dcp-field" }, h("label", { htmlFor: "dcp-create-kind" }, tr("类型", "Type")),
      h("select", { id: "dcp-create-kind", className: "dcp-select", value: kind, disabled, onChange: (event) => setKind(event.target.value) },
        available.length ? h("option", { value: "catalog" }, tr("内置提供方", "Built-in provider")) : null,
        h("option", { value: "custom" }, tr("自定义提供方", "Custom provider")))),
    kind === "catalog" ? h("div", { className: "dcp-field" }, h("label", { htmlFor: "dcp-create-catalog" }, tr("提供方", "Provider")),
      h("select", { id: "dcp-create-catalog", className: "dcp-select", value: chosen, disabled, onChange: (event) => setChosen(event.target.value) },
        available.map((item) => h("option", { value: item.provider, key: item.provider }, item.displayName ?? item.provider)))) :
      h(React.Fragment, null,
        h("div", { className: "dcp-field" }, h("label", { htmlFor: "dcp-create-route" }, tr("提供方 ID", "Provider ID")),
          h("input", { id: "dcp-create-route", className: "dcp-input", value: route, disabled, placeholder: "acme-gateway", onChange: (event) => setRoute(event.target.value) })),
        h("div", { className: "dcp-field" }, h("label", { htmlFor: "dcp-create-name" }, tr("显示名称", "Display name")),
          h("input", { id: "dcp-create-name", className: "dcp-input", value: name, disabled, onChange: (event) => setName(event.target.value) })),
        h("div", { className: "dcp-field" }, h("label", { htmlFor: "dcp-create-url" }, tr("接口地址", "Endpoint")),
          h("input", { id: "dcp-create-url", className: "dcp-input", type: "url", value: baseURL, disabled, placeholder: "https://api.example.com/v1", onChange: (event) => setBaseURL(event.target.value) })),
        h("div", { className: "dcp-field" }, h("label", { htmlFor: "dcp-create-api" }, tr("协议", "Protocol")),
          h("select", { id: "dcp-create-api", className: "dcp-select", value: protocol || protocols[0] || "", disabled, onChange: (event) => setProtocol(event.target.value) },
            protocols.map((item) => h("option", { value: item, key: item }, item)))),
        h("div", { className: "dcp-field" }, h("label", { htmlFor: "dcp-create-model" }, tr("首个模型 ID", "First model ID")),
          h("input", { id: "dcp-create-model", className: "dcp-input", value: modelId, disabled, onChange: (event) => setModelId(event.target.value) }))),
    h("div", { className: "dcp-field" }, h("label", { htmlFor: "dcp-create-key" }, "API Key"),
      h("input", { id: "dcp-create-key", className: "dcp-input", type: "password", autoComplete: "off", value: key,
        disabled: busy || submitting, onChange: (event) => setKey(event.target.value) }),
      h("p", { className: "dcp-help" }, tr("可留空；密钥单独存入 dsh 凭据库", "Optional; stored separately in dsh credentials"))),
    failure ? h("p", { className: "dcp-error", role: "alert" }, failure) : null,
    h("div", { className: "dcp-actions" },
      h("button", { type: "button", className: "dcp-button", disabled: submitting, onClick: () => onClose(committed) }, tr("关闭", "Close")),
      h("button", { type: "button", className: "dcp-button dcp-button-primary", disabled: busy || submitting || (!committed && kind === "catalog" && !chosen), onClick: submit },
        submitting ? tr("保存中", "Saving") : committed ? tr("重试保存密钥", "Retry key") : tr("添加", "Add"))));
}

function ModelRow({ view, route, model, mode, readOnly, busy, expanded, onToggle, onWrite, onDelete }) {
  const [name, setName] = React.useState(typeof model.name === "string" ? model.name : "");
  const [nameDirty, setNameDirty] = React.useState(false);
  const [failure, setFailure] = React.useState("");
  React.useEffect(() => {
    if (!nameDirty) setName(typeof model.name === "string" ? model.name : "");
  }, [model.id, model.name, nameDirty]);
  const saveName = async () => {
    const next = name.trim() || undefined;
    if (next === (typeof model.name === "string" ? model.name : undefined)) {
      setNameDirty(false);
      return;
    }
    try {
      const error = await onWrite(patchModelOperation(view, route, model.id, { name: next }));
      if (error) throw new Error(error);
      setNameDirty(false);
      setFailure("");
    } catch (error) { setFailure(error.message); }
  };
  let source;
  let sourceFailure;
  try { source = editableModel(view, route, model.id); }
  catch (error) { sourceFailure = error.message; }
  const effective = model;
  const modelReadOnly = readOnly || mode === "inherited";
  const expandedContent = sourceFailure ? h("p", { className: "dcp-error", role: "alert" }, sourceFailure) : source ? h(React.Fragment, null,
    h(CommonEditor, { key: `${route}:${model.id}:common`, source, effective, readOnly: modelReadOnly, busy,
      save: (changes) => { try { return onWrite(patchModelOperation(view, route, model.id, changes)); }
        catch (error) { return Promise.resolve(error.message); } } }),
    h("details", { className: "dcp-customized" },
      h("summary", { className: "dcp-customized-summary" }, tr("高级 JSON", "Advanced JSON")),
      h("div", { className: "dcp-customized-body" },
        h(AdvancedEditor, { key: `${route}:${model.id}:advanced`, source, readOnly: modelReadOnly, busy,
          save: (next) => { try { return onWrite(replaceModelOperation(view, route, model.id, next)); }
            catch (error) { return Promise.resolve(error.message); } } })))
  ) : null;
  return h("div", { className: "dcp-model-entry" },
    h("div", { className: "dcp-model-row" },
      h("input", { className: "dcp-input", value: model.id, readOnly: true,
        "aria-label": tr(`模型 ID ${model.id}`, `Model ID ${model.id}`), title: tr("模型 ID 不可在此处修改", "Model ID is fixed for this editor") }),
      h("input", { className: "dcp-input dcp-model-name", value: name, disabled: modelReadOnly || busy,
        placeholder: tr("模型名称", "Model name"), "aria-label": tr(`模型名称 ${model.id}`, `Model name ${model.id}`),
        onChange: (event) => { setName(event.target.value); setNameDirty(true); setFailure(""); }, onBlur: saveName,
        onKeyDown: (event) => { if (event.key === "Enter") event.currentTarget.blur(); } }),
      h("button", { type: "button", className: "dcp-button dcp-icon-button", "aria-expanded": expanded,
        "aria-label": expanded ? tr(`收起模型 ${model.id}`, `Collapse model ${model.id}`) : tr(`展开模型 ${model.id}`, `Expand model ${model.id}`),
        title: expanded ? tr("收起高级配置", "Collapse advanced settings") : tr("展开高级配置", "Expand advanced settings"),
        onClick: onToggle }, expanded ? "⌄" : "›"),
      mode === "listed" ? h("button", { type: "button", className: "dcp-button dcp-icon-button dcp-icon-button-danger",
        disabled: modelReadOnly || busy || view.user.providers[route].models.length === 1,
        title: view.user.providers[route].models.length === 1 ? tr("至少保留一个模型", "Keep at least one model") : tr("删除模型", "Remove model"),
        "aria-label": tr(`删除模型 ${model.id}`, `Remove model ${model.id}`), onClick: onDelete }, "×") : null),
    failure ? h("p", { className: "dcp-error", role: "alert" }, failure) : null,
    expanded ? h("div", { className: "dcp-model-advanced" }, expandedContent) : null);
}

function ModelCatalog({ view, route, mode, models, catalog, writable, busy, onWrite, onDiscover, query, setQuery }) {
  const [expanded, setExpanded] = React.useState(() => new Set());
  const [adding, setAdding] = React.useState(false);
  const [newModelId, setNewModelId] = React.useState("");
  const [failure, setFailure] = React.useState("");
  const normalizedQuery = query.trim().toLowerCase();
  const shownModels = normalizedQuery ? models.filter((model) => model.id.toLowerCase().includes(normalizedQuery) ||
    String(model.name ?? "").toLowerCase().includes(normalizedQuery)) : models;
  const addModel = async () => {
    const id = newModelId.trim();
    if (!id) return;
    try {
      const error = await onWrite(addModelOperation(view, route, { id }));
      if (error) throw new Error(error);
      setNewModelId(""); setAdding(false); setFailure(""); setExpanded((current) => new Set(current).add(id));
    } catch (error) { setFailure(error.message); }
  };
  return h("section", { className: "dcp-model-catalog", "aria-label": tr("模型", "Models") },
    h("div", { className: "dcp-model-catalog-head" },
      h("div", { className: "dcp-model-catalog-heading" },
        h("span", { className: "dcp-model-catalog-title" }, tr("模型", "Models")),
        h("span", { className: "dcp-model-catalog-meta" }, mode === "listed" ? tr("用户配置", "Customized") :
          mode === "inherited" ? tr("组合继承 · 只读", "Inherited · read-only") : tr("内置目录", "Built-in catalog"))),
      mode === "catalog" ? h("button", { type: "button", className: "dcp-button dcp-button-small", disabled: busy || catalog?.status === "loading", onClick: onDiscover },
        catalog?.status === "loading" ? tr("获取中", "Fetching") : tr("获取模型", "Fetch models")) : null),
    h("input", { className: "dcp-search", type: "search", value: query, disabled: busy,
      placeholder: tr("搜索模型", "Search models"), "aria-label": tr("搜索模型", "Search models"), onChange: (event) => setQuery(event.target.value) }),
    catalog?.status === "error" ? h("p", { className: "dcp-error", role: "alert" }, catalog.error) : null,
    failure ? h("p", { className: "dcp-error", role: "alert" }, failure) : null,
    catalog?.status === "loading" && !models.length ? h("div", { className: "dcp-skeleton" }) : null,
    shownModels.length ? h("div", { className: "dcp-model-list" }, shownModels.map((model) => h(ModelRow, { key: model.id, view, route, model, mode,
      readOnly: !writable, busy, expanded: expanded.has(model.id), onToggle: () => setExpanded((current) => {
        const next = new Set(current); if (!next.delete(model.id)) next.add(model.id); return next;
      }), onWrite, onDelete: async () => {
        if (!window.confirm(tr(`删除模型 ${model.id}？`, `Delete model ${model.id}?`))) return;
        try {
          const error = await onWrite(removeModelOperation(view, route, model.id));
          if (error) throw new Error(error);
          setFailure("");
        } catch (error) { setFailure(error.message); }
      } }))) :
      catalog?.status !== "loading" ? h("p", { className: "dcp-model-empty" }, tr("没有可配置模型", "No configurable models")) : null,
    mode === "listed" ? h("div", { className: "dcp-actions dcp-actions-start" }, adding ? h(React.Fragment, null,
      h("input", { className: "dcp-input", value: newModelId, disabled: busy, autoFocus: true,
        placeholder: tr("模型 ID", "Model ID"), "aria-label": tr("新模型 ID", "New model ID"), onChange: (event) => setNewModelId(event.target.value),
        onKeyDown: (event) => { if (event.key === "Enter") addModel(); } }),
      h("button", { type: "button", className: "dcp-button dcp-button-primary dcp-button-small", disabled: busy || !newModelId.trim(), onClick: addModel }, tr("添加", "Add")),
      h("button", { type: "button", className: "dcp-button dcp-button-small", disabled: busy, onClick: () => { setAdding(false); setNewModelId(""); } }, tr("取消", "Cancel"))) :
      h("button", { type: "button", className: "dcp-button dcp-add-model", disabled: !writable || busy, onClick: () => setAdding(true) }, "＋ ", tr("添加模型", "Add model"))) : null);
}

function ProviderEditor({ view, route, schema, api, writable, busy, onWrite, onRemoved, models, mode, catalog, onDiscover }) {
  const profile = providerProfile(view, route);
  const effective = getAt(view.value, ["providers", route]) ?? {};
  const ref = effective.apiKeyEnv || derivedKeyRef(route);
  const [draft, setDraft] = React.useState(() => ({
    displayName: profile.displayName ?? "", baseURL: profile.baseURL ?? "", api: profile.api ?? ""
  }));
  const [advanced, setAdvanced] = React.useState(false);
  const [json, setJson] = React.useState(() => JSON.stringify(profile, null, 2));
  const [key, setKey] = React.useState("");
  const [credential, setCredential] = React.useState();
  const [failure, setFailure] = React.useState("");
  const [status, setStatus] = React.useState("");
  const [working, setWorking] = React.useState(false);
  const [dirty, setDirty] = React.useState(false);
  const [jsonDirty, setJsonDirty] = React.useState(false);
  const [jsonRevision, setJsonRevision] = React.useState(view.revision);
  const protocols = React.useMemo(() => protocolChoices(view, schema), [view?.schema, schema]);
  React.useEffect(() => {
    let active = true;
    setCredential(undefined);
    api.credentials.describe([ref]).then((result) => {
      if (active) setCredential(result.ok ? result.value[ref] ?? { configured: false, writable: true } : { error: result.error.message });
    }).catch((error) => { if (active) setCredential({ error: error.message }); });
    return () => { active = false; };
  }, [api, ref]);
  React.useEffect(() => {
    if (!dirty) setDraft({ displayName: profile.displayName ?? "", baseURL: profile.baseURL ?? "", api: profile.api ?? "" });
    if (!jsonDirty) { setJson(JSON.stringify(profile, null, 2)); setJsonRevision(view.revision); }
  }, [JSON.stringify(profile), view.revision]);
  const change = (field, value) => {
    setDraft((current) => ({ ...current, [field]: value })); setDirty(true); setFailure(""); setStatus("");
  };
  const save = async (operation, expectedRevision) => {
    setFailure(""); setStatus(""); setWorking(true);
    try {
      const error = await onWrite(operation, expectedRevision);
      if (error) throw new Error(error);
      setDirty(false); setJsonDirty(false); setStatus(tr("已保存", "Saved"));
    } catch (error) { setFailure(error.message); }
    finally { setWorking(false); }
  };
  const saveCommon = () => {
    try {
      const next = Object.fromEntries(COMMON_PROVIDER_FIELDS.map((field) => [field, draft[field].trim() || undefined]));
      if (next.baseURL && !validUrl(next.baseURL)) throw new Error(tr("接口地址必须是 http 或 https URL", "Endpoint must be an http or https URL"));
      if (next.api && !protocols.includes(next.api)) throw new Error(tr("不支持的协议", "Unsupported protocol"));
      save(patchProviderOperation(view, route, next));
    } catch (error) { setFailure(error.message); }
  };
  const saveJson = () => {
    try {
      const next = JSON.parse(json);
      if (!next || Array.isArray(next) || typeof next !== "object") throw new Error(tr("提供方 JSON 必须是对象", "Provider JSON must be an object"));
      save(replaceProviderOperation(view, route, next), jsonRevision);
    } catch (error) { setFailure(error.message); }
  };
  const saveKey = async () => {
    if (jsonDirty) { setFailure(tr("请先保存或放弃高级 JSON 草稿", "Save or discard the Advanced JSON draft first")); return; }
    const invalid = keyFailure(key);
    if (invalid) { setFailure(invalid); return; }
    if (!key) return;
    setWorking(true); setFailure(""); setStatus("");
    try {
      if (!effective.apiKeyEnv) {
        const error = await onWrite({ op: "set", path: ["providers", route, "apiKeyEnv"], value: ref });
        if (error) throw new Error(error);
      }
      const result = await api.credentials.set(ref, key);
      if (!result.ok) throw new Error(result.error.message);
      setKey(""); setCredential({ configured: true, writable: true }); setStatus(tr("密钥已保存", "Key saved"));
    } catch (error) { setFailure(error.message); }
    finally { setWorking(false); }
  };
  const remove = async () => {
    if (!window.confirm(tr(`删除提供方 ${route}？其用户模型配置也将删除。`, `Delete provider ${route} and its user model settings?`))) return;
    setWorking(true); setFailure("");
    try {
      const error = await onWrite(removeProviderOperation(view, route));
      if (error) throw new Error(error);
      if (effective.apiKeyEnv === derivedKeyRef(route) && credential?.configured && credential.writable) {
        const result = await api.credentials.unset(ref);
        if (!result.ok) {
          onRemoved(tr("提供方已删除，但密钥清理失败：", "Provider deleted, but key cleanup failed: ") + result.error.message);
          return;
        }
      }
      onRemoved();
    } catch (error) { setFailure(error.message); }
    finally { setWorking(false); }
  };
  const disabled = !writable || busy || working;
  return h("div", { className: "dcp-provider-editor" },
    h("div", { className: "dcp-field" }, h("label", { htmlFor: `dcp-provider-key-${route}` }, "API Key"),
      h("input", { id: `dcp-provider-key-${route}`, className: "dcp-input", type: "password", autoComplete: "off", value: key,
        disabled: disabled || credential?.writable === false, placeholder: credential?.configured ? tr("已配置 · 输入新密钥以替换", "Configured · enter a new key to replace") : tr("未配置", "Not configured"),
        onChange: (event) => { setKey(event.target.value); setFailure(""); } }),
      h("p", { className: "dcp-help" }, credential?.error || tr("密钥存入凭据库，不写入设置 JSON", "Stored in credentials, not settings JSON"))),
    h("details", { className: "dcp-customized" },
      h("summary", { className: "dcp-customized-summary" }, tr("自定义设置", "Customized settings")),
      h("div", { className: "dcp-customized-body" },
        h("div", { className: "dcp-field" }, h("label", { htmlFor: `dcp-provider-name-${route}` }, tr("显示名称", "Display name")),
          h("input", { id: `dcp-provider-name-${route}`, className: "dcp-input", value: draft.displayName, disabled, placeholder: effective.displayName || route,
            onChange: (event) => change("displayName", event.target.value) })),
        h("div", { className: "dcp-field" }, h("label", { htmlFor: `dcp-provider-url-${route}` }, tr("接口地址", "Endpoint")),
          h("input", { id: `dcp-provider-url-${route}`, className: "dcp-input", type: "url", value: draft.baseURL, disabled,
            placeholder: effective.baseURL || tr("使用目录默认地址", "Catalog endpoint"), onChange: (event) => change("baseURL", event.target.value) })),
        h("div", { className: "dcp-field" }, h("label", { htmlFor: `dcp-provider-api-${route}` }, tr("协议", "Protocol")),
          h("select", { id: `dcp-provider-api-${route}`, className: "dcp-select", value: draft.api, disabled, onChange: (event) => change("api", event.target.value) },
            h("option", { value: "" }, tr("继承目录", "Inherit catalog")), protocols.map((item) => h("option", { value: item, key: item }, item)))),
        h("div", { className: "dcp-actions" },
          h("button", { type: "button", className: "dcp-button dcp-button-primary", disabled: disabled || !dirty, onClick: saveCommon }, tr("保存设置", "Save settings"))),
        h("details", { className: "dcp-customized" },
          h("summary", { className: "dcp-customized-summary" }, tr("高级 JSON", "Advanced JSON")),
          h("div", { className: "dcp-customized-body" },
            h("textarea", { className: "dcp-json", value: json, disabled, spellCheck: false, "aria-label": tr("当前提供方 JSON", "Current provider JSON"),
              onChange: (event) => { if (!jsonDirty) setJsonRevision(view.revision); setJson(event.target.value); setJsonDirty(true); setFailure(""); } }),
            h("div", { className: "dcp-actions" },
              h("button", { type: "button", className: "dcp-button dcp-button-small", disabled: disabled || !jsonDirty,
                onClick: () => { setJson(JSON.stringify(profile, null, 2)); setJsonRevision(view.revision); setJsonDirty(false); setFailure(""); } }, tr("重新加载", "Reload")),
              h("button", { type: "button", className: "dcp-button dcp-button-primary dcp-button-small", disabled: disabled || !jsonDirty, onClick: saveJson }, tr("保存 JSON", "Save JSON"))))))),
    h(ModelCatalog, { view, route, mode, models, catalog, writable, busy: disabled, onWrite, onDiscover }),
    h("div", { className: "dcp-actions" },
      providerRemovable(view, route) ? h("button", { type: "button", className: "dcp-button dcp-button-danger", disabled, onClick: remove }, tr("删除提供方", "Remove provider")) : null,
      h("button", { type: "button", className: "dcp-button dcp-button-primary", disabled: disabled || !key || jsonDirty || credential?.writable === false,
        title: jsonDirty ? tr("先处理高级 JSON 草稿", "Resolve Advanced JSON draft first") : undefined, onClick: saveKey }, tr("保存密钥", "Save key"))),
    failure ? h("p", { className: "dcp-error", role: "alert" }, failure) : null,
    status ? h("p", { className: "dcp-status", role: "status" }, status) : null);
}

function ModelConfigSection({ api, schema }) {
  const [view, setView] = React.useState();
  const [writable, setWritable] = React.useState(false);
  const [loading, setLoading] = React.useState(true);
  const [failure, setFailure] = React.useState("");
  const [route, setRoute] = React.useState("");
  const [directory, setDirectory] = React.useState([]);
  const [directoryError, setDirectoryError] = React.useState("");
  const [addingProvider, setAddingProvider] = React.useState(false);
  const [catalogs, setCatalogs] = React.useState({});
  const [query, setQuery] = React.useState("");
  const [busy, setBusy] = React.useState(false);

  const refresh = React.useCallback(async () => {
    const response = await api.settings.describe();
    if (!response.ok) throw new Error(response.error.message);
    const namespace = response.value.namespaces.find((item) => item.ns === NS);
    if (!namespace) throw new Error(tr("llm-pi-ai 未注册", "llm-pi-ai is not registered"));
    setView(namespace);
    setWritable(response.value.writable);
    setFailure("");
    setLoading(false);
  }, [api]);

  React.useEffect(() => {
    let active = true;
    refresh().catch((error) => { if (active) { setFailure(error.message); setLoading(false); } });
    const dispose = api.subscribe(() => refresh().catch((error) => { if (active) setFailure(error.message); }));
    return () => { active = false; dispose(); };
  }, [api, refresh]);

  const loadDirectory = React.useCallback(async (active = () => true) => {
    try {
      const result = await api.llm.listConfigurableProviders();
      if (!result.ok) throw new Error(result.error.message);
      if (!active()) return;
      setDirectory(result.value.filter((entry) => entry.settingsNs === NS));
      setDirectoryError("");
    } catch (error) { if (active()) setDirectoryError(error.message); }
  }, [api]);

  React.useEffect(() => {
    let active = true;
    loadDirectory(() => active);
    return () => { active = false; };
  }, [loadDirectory]);

  const profiles = getAt(view?.value, ["providers"]) ?? {};
  const providers = Object.entries(profiles).map(([id, profile]) => ({
    id,
    name: typeof profile?.displayName === "string" && profile.displayName ? profile.displayName :
      directory.find((entry) => entry.provider === id)?.displayName ?? id
  }));
  const providerIds = providers.map((provider) => provider.id).join("\0");
  const [credentialStates, setCredentialStates] = React.useState({});

  React.useEffect(() => {
    let active = true;
    const refs = providers.map((provider) => getAt(view?.value, ["providers", provider.id, "apiKeyEnv"]))
      .filter((ref) => typeof ref === "string" && ref.length > 0);
    if (!refs.length) { setCredentialStates({}); return () => { active = false; }; }
    api.credentials.describe(refs).then((result) => {
      if (!active || !result.ok) return;
      setCredentialStates(result.value);
    }).catch((error) => { if (active) setFailure(error.message); });
    return () => { active = false; };
  }, [api, providerIds, view?.revision]);

  React.useEffect(() => {
    if (route && !providers.some((provider) => provider.id === route)) {
      setRoute(providers[0]?.id ?? "");
    }
  }, [providerIds, route]);

  React.useEffect(() => {
    if (!view || !route) return;
    const mode = modelMode(view, route);
    if (mode !== "catalog") return;
    let active = true;
    setCatalogs((current) => ({ ...current, [route]: { status: "loading", models: current[route]?.models ?? [] } }));
    api.llm.discoverModels(NS, { provider: route }).then((response) => {
      if (!active) return;
      setCatalogs((current) => ({ ...current, [route]: response.ok
        ? { status: "ready", models: response.value }
        : { status: "error", models: current[route]?.models ?? [], error: response.error.message } }));
    }).catch((error) => {
      if (active) setCatalogs((current) => ({ ...current, [route]: { status: "error", models: [], error: error.message } }));
    });
    return () => { active = false; };
  }, [api, route, view?.revision]);

  const discovered = catalogs[route]?.models ?? [];
  const models = view && route ? modelEntries(view, route, discovered) : [];

  const saveOperation = async (operation, expectedRevision) => {
    if (!view || busy) return tr("配置尚未就绪", "Settings are not ready");
    setBusy(true);
    try {
      const outcome = await commitOperation(api, schema, view, operation, expectedRevision ?? view.revision);
      if (outcome.kind === "conflict") {
        await refresh();
        return expectedRevision === undefined
          ? tr("配置已被其他编辑更新，请核对后重试", "Settings changed elsewhere; review and retry")
          : tr("配置已被其他编辑更新，请核对 JSON 草稿后重新加载", "Settings changed elsewhere; review and reload the JSON draft");
      }
      if (outcome.kind === "invalid" || outcome.kind === "rejected") return outcome.message;
      setView(outcome.view);
      return undefined;
    } catch (error) { return error.message; }
    finally { setBusy(false); }
  };

  const mode = view && route ? modelMode(view, route) : "catalog";
  const available = availableCatalogProviders(directory, providers.map((provider) => provider.id));
  const discover = () => {
    if (!view || !route) return;
    setCatalogs((current) => ({ ...current, [route]: { status: "loading", models: current[route]?.models ?? [] } }));
    api.llm.discoverModels(NS, { provider: route }).then((response) => {
      setCatalogs((current) => ({ ...current, [route]: response.ok
        ? { status: "ready", models: response.value }
        : { status: "error", models: current[route]?.models ?? [], error: response.error.message } }));
    }).catch((error) => setCatalogs((current) => ({ ...current, [route]: { status: "error", models: [], error: error.message } })));
  };
  const removeProvider = async (id) => {
    if (!window.confirm(tr(`删除提供方 ${id}？其用户模型配置也将删除。`, `Remove provider ${id} and its model settings?`))) return;
    const profile = getAt(view.value, ["providers", id]) ?? {};
    const error = await saveOperation(removeProviderOperation(view, id));
    if (error) { setFailure(error); return; }
    if (profile.apiKeyEnv === derivedKeyRef(id)) {
      const result = await api.credentials.unset(profile.apiKeyEnv);
      if (!result.ok) setFailure(tr("提供方已删除，但密钥清理失败：", "Provider removed, but key cleanup failed: ") + result.error.message);
    }
    setRoute("");
  };

  if (loading) return h("div", { className: "dcp-page", "aria-busy": true },
    h("h2", null, tr("模型配置", "Model configuration")),
    h("div", { className: "dcp-skeleton" }), h("div", { className: "dcp-skeleton" }));

  if (failure && !view) return h("div", { className: "dcp-page" },
    h("h2", null, tr("模型配置", "Model configuration")),
    h("p", { className: "dcp-error", role: "alert" }, failure),
    h("button", { type: "button", className: "dcp-button", onClick: () => {
      setLoading(true); refresh().catch((error) => { setFailure(error.message); setLoading(false); });
    } }, tr("重试", "Retry")));

  return h("div", { className: "dcp-page" },
    h("h2", null, tr("模型配置", "Model configuration")),
    h("p", { className: "dcp-intro" }, tr("管理自定义提供方及其模型。配置方式与官方模型页面保持一致。", "Manage custom providers and their models using the same layout as the built-in Models page.")),
    !writable ? h("p", { className: "dcp-notice", role: "status" }, tr("当前设置为只读", "Settings are read-only")) : null,
    failure ? h("p", { className: "dcp-error", role: "alert" }, failure) : null,
    directoryError ? h("div", { className: "dcp-actions dcp-actions-start" },
      h("p", { className: "dcp-error", role: "alert" }, directoryError),
      h("button", { type: "button", className: "dcp-button dcp-button-small", onClick: () => loadDirectory() }, tr("重试", "Retry"))) : null,
    providers.length ? h("ul", { className: "dcp-provider-list" }, providers.map((provider) => {
      const kind = providerKind(view, provider.id, directory);
      const open = route === provider.id && !addingProvider;
      const profile = getAt(view.value, ["providers", provider.id]) ?? {};
      const credential = typeof profile.apiKeyEnv === "string" ? credentialStates[profile.apiKeyEnv] : undefined;
      const keyConfigured = credential?.configured === true;
      const keyMissing = credential?.configured === false;
      return h("li", { key: provider.id, className: "dcp-provider-card" },
        h("div", { className: "dcp-provider-head" },
          h("span", { className: "dcp-provider-identity" },
            h("span", { className: "dcp-provider-name" }, provider.name),
            provider.name !== provider.id ? h("span", { className: "dcp-provider-route" }, provider.id) : null,
            kind === "custom" ? h("span", { className: "dcp-provider-tag" }, tr("自定义", "Custom")) : null,
            kind === "inherited" ? h("span", { className: "dcp-provider-tag" }, tr("组合继承", "Inherited")) : null,
            keyConfigured ? h("span", { className: "dcp-credential-dot dcp-credential-dot-configured", role: "img", title: tr("已配置 API Key", "API key configured"), "aria-label": tr("已配置 API Key", "API key configured") }) :
              keyMissing ? h("span", { className: "dcp-credential-dot dcp-credential-dot-missing", role: "img", title: tr("缺少 API Key", "API key missing"), "aria-label": tr("缺少 API Key", "API key missing") }) : null),
          h("span", { className: "dcp-provider-actions" },
            h("button", { type: "button", className: "dcp-button dcp-button-small", disabled: busy,
              onClick: () => { setAddingProvider(false); setRoute(open ? "" : provider.id); setQuery(""); setFailure(""); } }, open ? tr("收起", "Close") : tr("编辑", "Edit")),
            kind === "custom" ? h("button", { type: "button", className: "dcp-button dcp-button-danger dcp-button-small", disabled: !writable || busy,
              onClick: () => removeProvider(provider.id) }, tr("移除", "Remove")) : null)),
        open ? h(ProviderEditor, { key: provider.id, view, route: provider.id, schema, api, writable, busy, onWrite: saveOperation,
          models, mode, catalog: catalogs[provider.id], onDiscover: discover,
          onRemoved: (error) => { setRoute(""); if (error) setFailure(error); } }) : null);
    })) : h("p", { className: "dcp-empty" }, tr("尚无提供方", "No providers yet")),
    addingProvider ? h("div", { className: "dcp-add-card" }, h(CreateProvider, { view, schema, available, busy, api, initialKind: addingProvider, onWrite: saveOperation,
      onClose: (id) => { setAddingProvider(false); if (id) setRoute(id); } })) :
      h("div", { className: "dcp-add-block" },
        h("div", { className: "dcp-add-actions" },
          h("button", { type: "button", className: "dcp-button dcp-add-option", disabled: !writable || busy || available.length === 0,
            onClick: () => { setAddingProvider("catalog"); setFailure(""); } }, "＋ ", tr("添加内置提供方", "Add built-in provider")),
          h("button", { type: "button", className: "dcp-button dcp-add-option", disabled: !writable || busy,
            onClick: () => { setAddingProvider("custom"); setFailure(""); } }, "＋ ", tr("添加自定义提供方", "Add custom provider")))));
}

function apply(ctx) {
  const remote = ctx.get("remote");
  const api = {
    settings: ctx.get("remote.settings"),
    credentials: ctx.get("remote.credentials"),
    llm: ctx.get("remote.llm"),
    subscribe: (callback) => {
      const disposeSettings = remote.$on("settings/document-updated", (ns) => { if (ns === NS) callback(); });
      const disposeModels = remote.$on("llm/adapters-updated", callback);
      return () => { disposeSettings(); disposeModels(); };
    }
  };
  ctx.slots.inject("settings.section", () => ctx.slots.register({
    name: "settings.section",
    id: "model-configuration",
    order: 11,
    label: () => tr("模型配置", "Model configuration"),
    inject: () => ({ api, schema: ctx.settingsSchema })
  }, ModelConfigSection));
  ctx.effect(() => {
    if (document.getElementById("dsh-custom-provider-styles")) return;
    const style = document.createElement("style");
    style.id = "dsh-custom-provider-styles";
    style.textContent = css;
    document.head.append(style);
    return () => style.remove();
  });
}

    return { apply, inject };
  }
});
