/* Generated by scripts/build-client.mjs; edit client.source.js and config.js. */
window.__ModuleLoader__.load({
  id: "dsh-custom-provider",
  factory: (require) => {
    const React = require("react");
const NAMESPACE = "llm-pi-ai";
const COMMON_MODEL_FIELDS = ["name", "contextWindow", "maxTokens", "input", "reasoningEfforts"];

function getAt(value, path) {
  return path.reduce((current, key) => current == null ? undefined : current[key], value);
}

function hasAt(value, path) {
  if (!path.length) return value !== undefined;
  const parent = getAt(value, path.slice(0, -1));
  return parent != null && Object.hasOwn(parent, path.at(-1));
}

function isRecord(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function editObject(value, path, next, restore) {
  const [head, ...tail] = path;
  const result = { ...(isRecord(value) ? value : {}) };
  if (!tail.length) {
    if (restore) delete result[head];
    else result[head] = next;
  } else {
    result[head] = editObject(result[head], tail, next, restore);
    if (restore && Object.keys(result[head]).length === 0) delete result[head];
  }
  return result;
}

function modelMode(view, route) {
  const path = ["providers", route, "models"];
  const userModels = getAt(view.user, path);
  if (Array.isArray(userModels)) return userModels.length ? "listed" : "catalog";
  if (Array.isArray(getAt(view.base, path)) && getAt(view.base, path).length) return "inherited";
  return "catalog";
}

function findModel(models, modelId) {
  return Array.isArray(models) ? models.find((model) => model?.id === modelId) : undefined;
}

function editableModel(view, route, modelId) {
  const prefix = ["providers", route];
  const mode = modelMode(view, route);
  if (mode === "listed") {
    const model = findModel(getAt(view.user, [...prefix, "models"]), modelId);
    if (!model) throw new Error(`Model ${modelId} is not in the configured list`);
    return { ...model };
  }
  if (mode === "inherited") {
    const model = findModel(getAt(view.value, [...prefix, "models"]), modelId);
    if (!model) throw new Error(`Model ${modelId} is not in the inherited list`);
    return { ...model };
  }
  const override = getAt(view.user, [...prefix, "modelOverrides", modelId]);
  return { id: modelId, ...(isRecord(override) ? override : {}) };
}

function effectiveModel(view, route, modelId, catalogModel) {
  const prefix = ["providers", route];
  const mode = modelMode(view, route);
  if (mode === "listed" || mode === "inherited") {
    return findModel(getAt(view.value, [...prefix, "models"]), modelId);
  }
  const profile = getAt(view.value, prefix);
  const override = getAt(profile, ["modelOverrides", modelId]);
  const catalog = catalogModel ? {
    id: catalogModel.id,
    ...(catalogModel.name === undefined ? {} : { name: catalogModel.name }),
    ...(catalogModel.contextWindow === undefined ? {} : { contextWindow: catalogModel.contextWindow }),
    ...(catalogModel.maxTokens === undefined ? {} : { maxTokens: catalogModel.maxTokens }),
    ...(catalogModel.inputModalities === undefined ? {} : { input: [...catalogModel.inputModalities] })
  } : { id: modelId };
  const input = catalog.input ?? profile?.defaultInput;
  return {
    ...(profile?.defaultContextWindow === undefined ? {} : { contextWindow: profile.defaultContextWindow }),
    ...(profile?.defaultMaxTokens === undefined ? {} : { maxTokens: profile.defaultMaxTokens }),
    ...(input === undefined ? {} : { input }),
    ...catalog,
    ...(isRecord(override) ? override : {}),
    id: modelId
  };
}

function modelEntries(view, route, discovered = []) {
  const prefix = ["providers", route];
  const mode = modelMode(view, route);
  const profile = getAt(view.value, prefix);
  if (mode === "listed" || mode === "inherited") {
    return (Array.isArray(profile?.models) ? profile.models : []).map((model) => ({ ...model }));
  }
  const ids = [];
  for (const model of discovered) if (model?.id && !ids.includes(model.id)) ids.push(model.id);
  for (const id of Object.keys(profile?.modelOverrides ?? {})) if (!ids.includes(id)) ids.push(id);
  return ids.map((id) => effectiveModel(view, route, id, discovered.find((model) => model.id === id)));
}

function replaceModelOperation(view, route, modelId, nextModel) {
  if (!isRecord(nextModel)) throw new Error("Model JSON must be an object");
  if (nextModel.id !== modelId) throw new Error(`Model id must remain ${modelId}`);
  const prefix = ["providers", route];
  const mode = modelMode(view, route);
  if (mode === "inherited") throw new Error("The inherited model list cannot be edited without replacing the whole list");
  if (mode === "listed") {
    const path = [...prefix, "models"];
    const models = getAt(view.user, path);
    const index = models.findIndex((model) => model.id === modelId);
    if (index < 0) throw new Error(`Model ${modelId} is not in the configured list`);
    return { op: "set", path, value: models.map((model, at) => at === index ? { ...nextModel } : model) };
  }
  const path = [...prefix, "modelOverrides", modelId];
  const override = Object.fromEntries(Object.entries(nextModel).filter(([key]) => key !== "id"));
  if (Object.keys(override).length === 0) {
    return hasAt(view.user, path) ? { op: "unset", path } : undefined;
  }
  return { op: "set", path, value: override };
}

function patchModelOperation(view, route, modelId, changes) {
  const next = editableModel(view, route, modelId);
  for (const [key, value] of Object.entries(changes)) {
    if (!COMMON_MODEL_FIELDS.includes(key)) throw new Error(`Unsupported common model field: ${key}`);
    if (value === undefined) delete next[key];
    else next[key] = value;
  }
  return replaceModelOperation(view, route, modelId, next);
}

function parseModelJson(text, modelId) {
  let value;
  try { value = JSON.parse(text); }
  catch (error) { throw new Error(`Invalid JSON: ${error.message}`); }
  if (!isRecord(value)) throw new Error("Model JSON must be an object");
  if (value.id !== modelId) throw new Error(`Model id must remain ${modelId}`);
  return value;
}

function mergeLayers(base, user) {
  if (user === undefined) return base;
  if (!isRecord(base) || !isRecord(user)) return user;
  const merged = { ...base };
  for (const [key, value] of Object.entries(user)) merged[key] = mergeLayers(base[key], value);
  return merged;
}

function candidate(view, operation) {
  const operations = Array.isArray(operation) ? operation : operation ? [operation] : [];
  let user = view.user ?? {};
  for (const op of operations) user = editObject(user, op.path, op.value, op.op === "unset");
  return mergeLayers(view.base ?? {}, user);
}

async function commitOperation(api, schema, view, operation) {
  if (!operation) return { kind: "unchanged", view };
  let invalid;
  try {
    const root = schema.rehydrate(view.schema);
    invalid = schema.validate(root, candidate(view, operation));
  } catch (error) {
    return { kind: "invalid", message: error.message };
  }
  if (invalid) return { kind: "invalid", message: typeof invalid === "string" ? invalid : JSON.stringify(invalid) };
  try {
    const response = await api.settings.mutate(NAMESPACE, [operation], view.revision);
    if (response.ok) return { kind: "written", view: response.value };
    return response.error.code === "settings/conflict"
      ? { kind: "conflict", message: response.error.message }
      : { kind: "rejected", message: response.error.message };
  } catch (error) {
    return { kind: "rejected", message: error.message };
  }
}

const h = React.createElement;
const NS = NAMESPACE;
const inject = ["slots", "remote", "remote.settings", "remote.llm", "settingsSchema"];
const zh = typeof navigator !== "undefined" && navigator.language?.startsWith("zh");
const tr = (cn, en) => zh ? cn : en;
const STANDARD_REASONING = {
  off: null,
  minimal: "minimal",
  low: "low",
  medium: "medium",
  high: "high",
  xhigh: "xhigh",
  max: "max"
};

const css = `
.dcp-page { max-width: 980px; color: var(--dsw-alias-label-primary, inherit); display: flex; flex-direction: column; gap: 14px; }
.dcp-page h2 { margin: 0; font-size: 16px; font-weight: 500; line-height: 24px; }
.dcp-workspace { min-height: 520px; display: grid; grid-template-columns: minmax(190px, 240px) minmax(0, 1fr); border: .5px solid var(--dsw-alias-border-l4, #8886); border-radius: 8px; overflow: hidden; }
.dcp-nav { min-width: 0; padding: 12px 10px; border-right: .5px solid var(--dsw-alias-border-l3, #8885); background: var(--dsw-alias-bg-module-platform, transparent); }
.dcp-search, .dcp-input, .dcp-select, .dcp-json { box-sizing: border-box; width: 100%; color: inherit; background: var(--dsw-alias-bg-layer-1, transparent); border: .5px solid var(--dsw-alias-border-l4, #8887); border-radius: 6px; font: inherit; }
.dcp-search, .dcp-input, .dcp-select { height: 34px; padding: 0 10px; font-size: 13px; }
.dcp-search:focus, .dcp-input:focus, .dcp-select:focus, .dcp-json:focus { border-color: var(--dsw-alias-brand-primary, #2b8063); outline: none; }
.dcp-search::placeholder, .dcp-input::placeholder { color: var(--dsw-alias-label-dimmed, #777); }
.dcp-provider { margin-top: 10px; }
.dcp-provider-button, .dcp-model-button { box-sizing: border-box; width: 100%; border: 0; color: inherit; background: transparent; text-align: left; cursor: pointer; border-radius: 6px; font: inherit; }
.dcp-provider-button { min-height: 34px; padding: 6px 8px; font-size: 13px; font-weight: 500; }
.dcp-provider-button:hover, .dcp-model-button:hover { background: var(--dsw-alias-interactive-bg-hover, #8882); }
.dcp-provider-button[aria-expanded=true] { color: var(--dsw-alias-brand-primary, #23745a); }
.dcp-models { margin: 2px 0 0 8px; padding-left: 8px; border-left: .5px solid var(--dsw-alias-border-l3, #8885); }
.dcp-model-button { min-height: 32px; padding: 6px 8px; color: var(--dsw-alias-label-secondary, inherit); font-size: 12px; overflow-wrap: anywhere; }
.dcp-model-button[aria-current=true] { color: var(--dsw-alias-label-primary, inherit); background: var(--dsw-alias-interactive-bg-hover-solid, #8883); font-weight: 500; }
.dcp-content { min-width: 0; padding: 18px 20px; }
.dcp-model-head { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; margin-bottom: 14px; }
.dcp-model-title { min-width: 0; }
.dcp-model-title h3 { margin: 0; font-size: 15px; font-weight: 500; line-height: 22px; overflow-wrap: anywhere; }
.dcp-model-id { margin-top: 2px; color: var(--dsw-alias-label-tertiary, #777); font-family: var(--ds-font-family-code, ui-monospace, monospace); font-size: 12px; overflow-wrap: anywhere; }
.dcp-badge { flex: none; border: .5px solid var(--dsw-alias-border-l3, #8886); border-radius: 4px; padding: 2px 6px; color: var(--dsw-alias-label-secondary, inherit); font-size: 11px; line-height: 16px; }
.dcp-tabs { display: flex; gap: 2px; border-bottom: .5px solid var(--dsw-alias-border-l3, #8885); margin-bottom: 18px; }
.dcp-tab { height: 34px; border: 0; border-bottom: 2px solid transparent; color: var(--dsw-alias-label-secondary, inherit); background: transparent; padding: 0 12px; cursor: pointer; font: inherit; font-size: 13px; }
.dcp-tab[aria-selected=true] { border-bottom-color: var(--dsw-alias-brand-primary, #2b8063); color: var(--dsw-alias-label-primary, inherit); font-weight: 500; }
.dcp-form { display: flex; flex-direction: column; gap: 14px; }
.dcp-field { display: grid; grid-template-columns: minmax(120px, 160px) minmax(0, 1fr); align-items: center; gap: 8px 14px; }
.dcp-field label { color: var(--dsw-alias-label-secondary, inherit); font-size: 12px; font-weight: 500; }
.dcp-help { grid-column: 2; margin: -3px 0 0; color: var(--dsw-alias-label-tertiary, #777); font-size: 11px; line-height: 17px; }
.dcp-actions { display: flex; justify-content: flex-end; gap: 8px; padding-top: 4px; }
.dcp-button { box-sizing: border-box; height: 34px; border: .5px solid var(--dsw-alias-border-l3, #8887); border-radius: 6px; color: inherit; background: transparent; padding: 0 12px; cursor: pointer; font: inherit; font-size: 13px; }
.dcp-button:hover:not(:disabled) { background: var(--dsw-alias-interactive-bg-hover, #8882); }
.dcp-button-primary { border-color: transparent; background: var(--dsw-alias-button-primary-fill, #2b8063); color: var(--dsw-alias-label-primary-foreground, white); }
.dcp-button-primary:hover:not(:disabled) { background: var(--dsw-alias-button-primary-hover, #236b54); }
.dcp-button:disabled, .dcp-input:disabled, .dcp-select:disabled, .dcp-json:disabled { opacity: .48; cursor: default; }
.dcp-json { min-height: 360px; resize: vertical; padding: 12px; font-family: var(--ds-font-family-code, ui-monospace, monospace); font-size: 12px; line-height: 19px; tab-size: 2; }
.dcp-error, .dcp-status, .dcp-empty { margin: 8px 0; font-size: 12px; line-height: 18px; }
.dcp-error { color: var(--dsw-alias-state-error-primary, #b42332); white-space: pre-wrap; }
.dcp-status { color: var(--dsw-alias-state-success-primary, #21835a); }
.dcp-empty { color: var(--dsw-alias-label-tertiary, #777); }
.dcp-skeleton { height: 28px; margin: 5px 6px; border-radius: 5px; background: var(--dsw-alias-interactive-bg-hover, #8882); animation: dcp-pulse 1.2s ease-in-out infinite alternate; }
@keyframes dcp-pulse { to { opacity: .45; } }
.dcp-button:focus-visible, .dcp-provider-button:focus-visible, .dcp-model-button:focus-visible, .dcp-tab:focus-visible { outline: 2px solid var(--dsw-alias-brand-primary, #2b8063); outline-offset: 1px; }
@media (prefers-reduced-motion: reduce) { .dcp-skeleton { animation: none; } }
@media (max-width: 760px) {
  .dcp-workspace { grid-template-columns: minmax(0, 1fr); }
  .dcp-nav { border-right: 0; border-bottom: .5px solid var(--dsw-alias-border-l3, #8885); max-height: 260px; overflow-y: auto; }
  .dcp-content { padding: 16px 14px; }
  .dcp-field { grid-template-columns: minmax(0, 1fr); gap: 5px; }
  .dcp-help { grid-column: 1; }
}
`;

function sameJson(left, right) {
  return JSON.stringify(left) === JSON.stringify(right);
}

function inputMode(value) {
  if (!Array.isArray(value) || value.length === 0) return "inherit";
  if (value.length === 1 && value[0] === "text") return "text";
  if (value.includes("text") && value.includes("image")) return "image";
  return "custom";
}

function reasoningMode(value) {
  if (value === undefined) return "inherit";
  if (value === false) return "disabled";
  if (sameJson(value, STANDARD_REASONING)) return "standard";
  return "custom";
}

function commonDraft(source) {
  return {
    name: typeof source.name === "string" ? source.name : "",
    contextWindow: source.contextWindow === undefined ? "" : String(source.contextWindow),
    maxTokens: source.maxTokens === undefined ? "" : String(source.maxTokens),
    input: inputMode(source.input),
    reasoning: reasoningMode(source.reasoningEfforts)
  };
}

function positiveInteger(text, label) {
  if (text.trim() === "") return undefined;
  const value = Number(text);
  if (!Number.isSafeInteger(value) || value <= 0) throw new Error(tr(`${label}必须是正整数`, `${label} must be a positive integer`));
  return value;
}

function CommonEditor({ source, effective, readOnly, busy, save }) {
  const sourceKey = JSON.stringify(source);
  const initial = () => commonDraft(source);
  const [draft, setDraft] = React.useState(initial);
  const [dirty, setDirty] = React.useState(false);
  const [failure, setFailure] = React.useState("");
  const [saved, setSaved] = React.useState(false);
  React.useEffect(() => {
    if (!dirty) setDraft(initial());
  }, [sourceKey]);
  const change = (key, value) => {
    setDraft((current) => ({ ...current, [key]: value }));
    setDirty(true);
    setFailure("");
    setSaved(false);
  };
  const submit = async (restore = false) => {
    try {
      const changes = restore ? Object.fromEntries(COMMON_MODEL_FIELDS.map((key) => [key, undefined])) : {
        name: draft.name.trim() || undefined,
        contextWindow: positiveInteger(draft.contextWindow, tr("上下文窗口", "Context window")),
        maxTokens: positiveInteger(draft.maxTokens, tr("输出上限", "Output limit")),
        input: draft.input === "inherit" ? undefined : draft.input === "text" ? ["text"] :
          draft.input === "image" ? ["text", "image"] : source.input,
        reasoningEfforts: draft.reasoning === "inherit" ? undefined : draft.reasoning === "disabled" ? false :
          draft.reasoning === "standard" ? STANDARD_REASONING : source.reasoningEfforts
      };
      const error = await save(changes);
      setFailure(error ?? "");
      setSaved(!error);
      if (!error) setDirty(false);
    } catch (error) {
      setFailure(error.message);
      setSaved(false);
    }
  };
  const disabled = readOnly || busy;
  return h("div", { className: "dcp-form" },
    h("div", { className: "dcp-field" },
      h("label", { htmlFor: "dcp-name" }, tr("模型名称", "Model name")),
      h("input", { id: "dcp-name", className: "dcp-input", value: draft.name, disabled,
        placeholder: effective?.name ?? source.id, onChange: (event) => change("name", event.target.value) })),
    h("div", { className: "dcp-field" },
      h("label", { htmlFor: "dcp-reasoning" }, tr("推理能力", "Reasoning")),
      h("select", { id: "dcp-reasoning", className: "dcp-select", value: draft.reasoning, disabled,
        onChange: (event) => change("reasoning", event.target.value) },
        h("option", { value: "inherit" }, tr("继承提供方或目录", "Inherit provider or catalog")),
        h("option", { value: "disabled" }, tr("不支持推理", "Reasoning disabled")),
        h("option", { value: "standard" }, tr("标准推理档位", "Standard reasoning levels")),
        draft.reasoning === "custom" ? h("option", { value: "custom" }, tr("自定义档位（高级 JSON）", "Custom levels (Advanced JSON)")) : null)),
    h("div", { className: "dcp-field" },
      h("label", { htmlFor: "dcp-input" }, tr("输入类型", "Input types")),
      h("select", { id: "dcp-input", className: "dcp-select", value: draft.input, disabled,
        onChange: (event) => change("input", event.target.value) },
        h("option", { value: "inherit" }, tr("继承提供方或目录", "Inherit provider or catalog")),
        h("option", { value: "text" }, tr("文本", "Text")),
        h("option", { value: "image" }, tr("文本和图片", "Text and image")),
        draft.input === "custom" ? h("option", { value: "custom" }, tr("自定义（高级 JSON）", "Custom (Advanced JSON)")) : null)),
    h("div", { className: "dcp-field" },
      h("label", { htmlFor: "dcp-context" }, tr("上下文窗口", "Context window")),
      h("input", { id: "dcp-context", className: "dcp-input", type: "number", min: "1", step: "1",
        value: draft.contextWindow, disabled, placeholder: effective?.contextWindow === undefined ? "" : String(effective.contextWindow),
        onChange: (event) => change("contextWindow", event.target.value) })),
    h("div", { className: "dcp-field" },
      h("label", { htmlFor: "dcp-output" }, tr("输出上限", "Output limit")),
      h("input", { id: "dcp-output", className: "dcp-input", type: "number", min: "1", step: "1",
        value: draft.maxTokens, disabled, placeholder: effective?.maxTokens === undefined ? "" : String(effective.maxTokens),
        onChange: (event) => change("maxTokens", event.target.value) })),
    failure ? h("p", { className: "dcp-error", role: "alert" }, failure) : null,
    saved ? h("p", { className: "dcp-status", role: "status" }, tr("已保存", "Saved")) : null,
    readOnly ? h("p", { className: "dcp-empty" }, tr("此模型来自组合配置，当前只读", "This model is inherited from the composition and is read-only")) :
      h("div", { className: "dcp-actions" },
        h("button", { type: "button", className: "dcp-button", disabled: busy,
          onClick: () => submit(true) }, tr("恢复继承", "Restore inherited")),
        h("button", { type: "button", className: "dcp-button dcp-button-primary", disabled: busy || !dirty,
          onClick: () => submit(false) }, busy ? tr("保存中", "Saving") : tr("保存", "Save"))));
}

function AdvancedEditor({ source, readOnly, busy, save }) {
  const sourceKey = JSON.stringify(source);
  const formatted = () => JSON.stringify(source, null, 2);
  const [draft, setDraft] = React.useState(formatted);
  const [dirty, setDirty] = React.useState(false);
  const [failure, setFailure] = React.useState("");
  const [saved, setSaved] = React.useState(false);
  React.useEffect(() => {
    if (!dirty) setDraft(formatted());
  }, [sourceKey]);
  const format = () => {
    try {
      const value = parseModelJson(draft, source.id);
      setDraft(JSON.stringify(value, null, 2));
      setFailure("");
    } catch (error) { setFailure(error.message); }
  };
  const submit = async () => {
    try {
      const value = parseModelJson(draft, source.id);
      const error = await save(value);
      setFailure(error ?? "");
      setSaved(!error);
      if (!error) setDirty(false);
    } catch (error) {
      setFailure(error.message);
      setSaved(false);
    }
  };
  return h("div", null,
    h("textarea", { className: "dcp-json", value: draft, disabled: readOnly || busy, spellCheck: false,
      "aria-label": tr("当前模型 JSON", "Current model JSON"), onChange: (event) => {
        setDraft(event.target.value); setDirty(true); setFailure(""); setSaved(false);
      } }),
    failure ? h("p", { className: "dcp-error", role: "alert" }, failure) : null,
    saved ? h("p", { className: "dcp-status", role: "status" }, tr("已保存", "Saved")) : null,
    readOnly ? h("p", { className: "dcp-empty" }, tr("此模型来自组合配置，当前只读", "This model is inherited from the composition and is read-only")) :
      h("div", { className: "dcp-actions" },
        h("button", { type: "button", className: "dcp-button", disabled: busy, onClick: format }, tr("格式化", "Format")),
        h("button", { type: "button", className: "dcp-button dcp-button-primary", disabled: busy || !dirty,
          onClick: submit }, busy ? tr("保存中", "Saving") : tr("保存 JSON", "Save JSON"))));
}

function ModelConfigSection({ api, schema }) {
  const [view, setView] = React.useState();
  const [writable, setWritable] = React.useState(false);
  const [loading, setLoading] = React.useState(true);
  const [failure, setFailure] = React.useState("");
  const [route, setRoute] = React.useState("");
  const [modelId, setModelId] = React.useState("");
  const [catalogs, setCatalogs] = React.useState({});
  const [query, setQuery] = React.useState("");
  const [tab, setTab] = React.useState("common");
  const [busy, setBusy] = React.useState(false);

  const refresh = React.useCallback(async () => {
    const response = await api.settings.describe();
    if (!response.ok) throw new Error(response.error.message);
    const namespace = response.value.namespaces.find((item) => item.ns === NS);
    if (!namespace) throw new Error(tr("llm-pi-ai 未注册", "llm-pi-ai is not registered"));
    setView(namespace);
    setWritable(response.value.writable);
    setFailure("");
    setLoading(false);
  }, [api]);

  React.useEffect(() => {
    let active = true;
    refresh().catch((error) => { if (active) { setFailure(error.message); setLoading(false); } });
    const dispose = api.subscribe(() => refresh().catch((error) => { if (active) setFailure(error.message); }));
    return () => { active = false; dispose(); };
  }, [api, refresh]);

  const profiles = getAt(view?.value, ["providers"]) ?? {};
  const providers = Object.entries(profiles).map(([id, profile]) => ({
    id,
    name: typeof profile?.displayName === "string" && profile.displayName ? profile.displayName : id
  }));
  const providerIds = providers.map((provider) => provider.id).join("\0");

  React.useEffect(() => {
    if (!providers.some((provider) => provider.id === route)) {
      setRoute(providers[0]?.id ?? "");
      setModelId("");
    }
  }, [providerIds, route]);

  React.useEffect(() => {
    if (!view || !route) return;
    const mode = modelMode(view, route);
    if (mode !== "catalog") return;
    let active = true;
    setCatalogs((current) => ({ ...current, [route]: { status: "loading", models: current[route]?.models ?? [] } }));
    api.llm.discoverModels(NS, { provider: route }).then((response) => {
      if (!active) return;
      setCatalogs((current) => ({ ...current, [route]: response.ok
        ? { status: "ready", models: response.value }
        : { status: "error", models: current[route]?.models ?? [], error: response.error.message } }));
    }).catch((error) => {
      if (active) setCatalogs((current) => ({ ...current, [route]: { status: "error", models: [], error: error.message } }));
    });
    return () => { active = false; };
  }, [api, route, view?.revision]);

  const discovered = catalogs[route]?.models ?? [];
  const models = view && route ? modelEntries(view, route, discovered) : [];
  const modelIds = models.map((model) => model.id).join("\0");
  React.useEffect(() => {
    if (!models.some((model) => model.id === modelId)) setModelId(models[0]?.id ?? "");
  }, [modelIds, modelId]);

  const saveOperation = async (operation) => {
    if (!view || busy) return tr("配置尚未就绪", "Settings are not ready");
    setBusy(true);
    try {
      const outcome = await commitOperation(api, schema, view, operation);
      if (outcome.kind === "conflict") {
        await refresh();
        return tr("配置已被其他编辑更新，请核对后重试", "Settings changed elsewhere; review and retry");
      }
      if (outcome.kind === "invalid" || outcome.kind === "rejected") return outcome.message;
      setView(outcome.view);
      return undefined;
    } finally { setBusy(false); }
  };

  const selected = models.find((model) => model.id === modelId);
  let source;
  let sourceFailure;
  if (view && route && modelId) {
    try { source = editableModel(view, route, modelId); }
    catch (error) { sourceFailure = error.message; }
  }
  const mode = view && route ? modelMode(view, route) : "catalog";
  const readOnly = !writable || mode === "inherited";
  const normalizedQuery = query.trim().toLowerCase();
  const shownModels = normalizedQuery ? models.filter((model) =>
    model.id.toLowerCase().includes(normalizedQuery) || String(model.name ?? "").toLowerCase().includes(normalizedQuery)) : models;

  if (loading) return h("div", { className: "dcp-page", "aria-busy": true },
    h("h2", null, tr("模型配置", "Model configuration")),
    h("div", { className: "dcp-workspace" },
      h("div", { className: "dcp-nav" }, h("div", { className: "dcp-skeleton" }), h("div", { className: "dcp-skeleton" })),
      h("div", { className: "dcp-content" }, h("div", { className: "dcp-skeleton" }), h("div", { className: "dcp-skeleton" }))));

  if (failure && !view) return h("div", { className: "dcp-page" },
    h("h2", null, tr("模型配置", "Model configuration")),
    h("p", { className: "dcp-error", role: "alert" }, failure),
    h("button", { type: "button", className: "dcp-button", onClick: () => {
      setLoading(true); refresh().catch((error) => { setFailure(error.message); setLoading(false); });
    } }, tr("重试", "Retry")));

  return h("div", { className: "dcp-page" },
    h("h2", null, tr("模型配置", "Model configuration")),
    !writable ? h("p", { className: "dcp-error", role: "status" }, tr("当前设置为只读", "Settings are read-only")) : null,
    failure ? h("p", { className: "dcp-error", role: "alert" }, failure) : null,
    h("div", { className: "dcp-workspace" },
      h("nav", { className: "dcp-nav", "aria-label": tr("提供方和模型", "Providers and models") },
        h("input", { className: "dcp-search", type: "search", value: query,
          placeholder: tr("搜索模型", "Search models"), "aria-label": tr("搜索模型", "Search models"),
          onChange: (event) => setQuery(event.target.value) }),
        providers.length ? providers.map((provider) => {
          const active = provider.id === route;
          return h("div", { className: "dcp-provider", key: provider.id },
            h("button", { type: "button", className: "dcp-provider-button", "aria-expanded": active,
              onClick: () => { setRoute(provider.id); setModelId(""); setTab("common"); } }, provider.name),
            active ? h("div", { className: "dcp-models" },
              mode === "catalog" && catalogs[route]?.status === "loading" && models.length === 0
                ? [h("div", { className: "dcp-skeleton", key: "a" }), h("div", { className: "dcp-skeleton", key: "b" })]
                : shownModels.map((model) => h("button", { type: "button", className: "dcp-model-button", key: model.id,
                  "aria-current": model.id === modelId, onClick: () => { setModelId(model.id); setTab("common"); } }, model.name ?? model.id)),
              catalogs[route]?.status === "error" ? h("p", { className: "dcp-error", role: "alert" }, catalogs[route].error) : null,
              shownModels.length === 0 && catalogs[route]?.status !== "loading"
                ? h("p", { className: "dcp-empty" }, tr("没有可配置模型", "No configurable models")) : null) : null);
        }) : h("p", { className: "dcp-empty" }, tr("没有已配置的提供方", "No configured providers"))),
      h("main", { className: "dcp-content" },
        sourceFailure ? h("p", { className: "dcp-error", role: "alert" }, sourceFailure) :
        !source || !selected ? h("p", { className: "dcp-empty" }, tr("选择一个模型", "Select a model")) :
        h(React.Fragment, null,
          h("div", { className: "dcp-model-head" },
            h("div", { className: "dcp-model-title" },
              h("h3", null, selected.name ?? selected.id),
              h("div", { className: "dcp-model-id" }, `${route} / ${selected.id}`)),
            h("span", { className: "dcp-badge" }, mode === "listed" ? tr("自定义列表", "Custom list") :
              mode === "inherited" ? tr("组合继承", "Inherited") : tr("内置目录", "Built-in catalog"))),
          h("div", { className: "dcp-tabs", role: "tablist" },
            h("button", { type: "button", className: "dcp-tab", role: "tab", "aria-selected": tab === "common",
              onClick: () => setTab("common") }, tr("常用配置", "Common")),
            h("button", { type: "button", className: "dcp-tab", role: "tab", "aria-selected": tab === "advanced",
              onClick: () => setTab("advanced") }, tr("高级 JSON", "Advanced JSON"))),
          tab === "common" ? h(CommonEditor, { key: `${route}:${modelId}:common`, source, effective: selected,
            readOnly, busy, save: (changes) => {
              try { return saveOperation(patchModelOperation(view, route, modelId, changes)); }
              catch (error) { return Promise.resolve(error.message); }
            } }) :
          h(AdvancedEditor, { key: `${route}:${modelId}:advanced`, source, readOnly, busy,
            save: (next) => {
              try { return saveOperation(replaceModelOperation(view, route, modelId, next)); }
              catch (error) { return Promise.resolve(error.message); }
            }
          })))));
}

function apply(ctx) {
  const remote = ctx.get("remote");
  const api = {
    settings: ctx.get("remote.settings"),
    llm: ctx.get("remote.llm"),
    subscribe: (callback) => {
      const disposeSettings = remote.$on("settings/document-updated", (ns) => { if (ns === NS) callback(); });
      const disposeModels = remote.$on("llm/adapters-updated", callback);
      return () => { disposeSettings(); disposeModels(); };
    }
  };
  ctx.slots.inject("settings.section", () => ctx.slots.register({
    name: "settings.section",
    id: "model-configuration",
    order: 11,
    label: () => tr("模型配置", "Model configuration"),
    inject: () => ({ api, schema: ctx.settingsSchema })
  }, ModelConfigSection));
  ctx.effect(() => {
    if (document.getElementById("dsh-custom-provider-styles")) return;
    const style = document.createElement("style");
    style.id = "dsh-custom-provider-styles";
    style.textContent = css;
    document.head.append(style);
    return () => style.remove();
  });
}

    return { apply, inject };
  }
});
