import { readFile, writeFile } from "node:fs/promises";

const helpers = (await Promise.all(["config.js", "modelsdev.js"].map((name) =>
  readFile(new URL(`../lib/${name}`, import.meta.url), "utf8")))).join("\n").replace(/^export /gm, "");
const source = await readFile(new URL("../lib/client.source.js", import.meta.url), "utf8");
const bundle = `/* Generated by scripts/build-client.mjs; edit client.source.js, config.js and modelsdev.js. */
window.__ModuleLoader__.load({
  id: "dsh-custom-provider",
  factory: (require) => {
    const React = require("react");
${helpers}
${source}
    return { apply, inject };
  }
});
`;
await writeFile(new URL("../lib/client.js", import.meta.url), bundle, "utf8");
